### ISSUE TITLE
equilibrium: dask scheduler default incorrectly set to synchronous

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#101]
The default setting of the `scheduler` kwarg in `equilibrium` is `dask.async.get_sync`, which means that the computation is being performed sequentially on a single core. This is suboptimal for any line/map calculation.

It looks like that change slipped in about 9 months ago in an unrelated commit, which is one of many reasons why we now do code review.

**Comment by bocklund** [comment]
Is multiprocessing enough or should we set up a client by default?

**Comment by richardotis** [comment]
I think `scheduler` should be `dask.multiprocessing.get` by default, but if the number of calculations is "small", we should just fall back to `dask.async.get_sync` (or whatever it's called now in newer versions).

**Comment by richardotis** [comment]
We compute the number of calculations toward the bottom of `equilibrium()`

**Comment by bocklund** [comment]
Some examples from NIMS databases. I assumed that parallelization in dask was independent of the shape of the equilibrium calculation. That is, for calculation shape of (P,T,X) that the scaling of (1,1,N) is similar to (1,sqrt(N),sqrt(N)). Each point is sampled twice and averaged.

It appears that multiprocessing would be a poor choice for default. 

What are your thoughts then on client vs sync, where with client we will have to implicitly start a distributed client. I think maybe sync as the default is okay given that the biggest speedup was less than 2x even for 10k equilibrium calculations on 8 cores.

![al-ni](https://user-images.githubusercontent.com/7681751/28586738-c3a52f52-7142-11e7-8275-f9111aa19998.png)
![cu-zr_sau](https://user-images.githubusercontent.com/7681751/28586735-c39d07d2-7142-11e7-8351-75b41cc2f3cb.png)
![la-ti](https://user-images.githubusercontent.com/7681751/28586736-c39e46e2-7142-11e7-9d87-6eb7b8386fa2.png)
![mg-zn](https://user-images.githubusercontent.com/7681751/28586737-c39eee76-7142-11e7-8dcb-594f0ef69ca4.png)

**Comment by bocklund** [comment]
Log-log because why not 
![al-ni-log](https://user-images.githubusercontent.com/7681751/28586791-e3d00a4a-7142-11e7-95f0-b50ce5528d7c.png)
![cu-zr_sau-log](https://user-images.githubusercontent.com/7681751/28586790-e3ced224-7142-11e7-8af3-ca67bb821ee2.png)
![la-ti-log](https://user-images.githubusercontent.com/7681751/28586788-e3cbc520-7142-11e7-98e9-e3db2e1c94fa.png)
![mg-zn-log](https://user-images.githubusercontent.com/7681751/28586789-e3cdc6fe-7142-11e7-9638-79060fc513c1.png)

**Comment by richardotis** [comment]
@bocklund Thanks for running this test. It appears that "sync" would be a sensible default up to, perhaps, 100 calculations, at which point we probably should switch to the distributed scheduler.

What do you think about leaving our current default scheduler (distributed), and just increasing the [threshold `num_calcs` value](https://github.com/pycalphad/pycalphad/blob/29aa7da67f558ec61b5a0c0da0096f40260295c4/pycalphad/core/equilibrium.py#L312) for switching to the scheduler?

**Comment by richardotis** [comment]
On a second read, it would appear that that value only controls the way calculations are chunked, so perhaps changing the default scheduler to "sync" is the best option.

**Comment by bocklund** [comment]
In OOB discussion:

* Possible poor chunking [here](https://github.com/pycalphad/pycalphad/blob/29aa7da67f558ec61b5a0c0da0096f40260295c4/pycalphad/core/equilibrium.py#L312)
* Certain `conditions_per_chunk_per_axis` cause an error to be raised.

**Comment by richardotis** [comment]
I double checked the chunking code and it is fine. (`chunk_grid` is actually an index array, not the actual chunk list.) Still not sure on `conditions_per_chunk_per_axis`.

**Comment by bocklund** [comment]
Tried to look at this some more. It seems like we are chunking the way we intend by the graph 

![mydask](https://user-images.githubusercontent.com/7681751/38264878-59a5c000-3742-11e8-85f7-6c5bacf08ac9.png)


However I was running into some issues that seemed to be related to trying to pickle things when running on multiple processes.

**Comment by bocklund** [comment]
I'm wondering if this is related to all our delayed having `pure=False` - maybe the dask scheduler is not calling `_solve_eq_at_conditions` because it's impure. The only thing modified/hidden state for the number of conditions 

```python
            job = delayed(_solve_eq_at_conditions, pure=False)(comps, prop_slice, phase_records, grid,
                                                               list(str_conds.keys()), state_variables, verbose, solver=solver)
```
is the `prop_slice`, which is a unique slice of the properties, which different solve_eq_at_conditions should be able to modify concurrently.

**Comment by bocklund** [comment]
Setting `pure=True` on 5959be6439f4a0d2e0522c41f01986f761340da5 did not realize a performance improvement.
