### ISSUE TITLE
xarray Datasets are not correctly serialized to netcdf

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#111]
```python
import numpy as np
import xarray as xr
import datetime
data = xr.DataArray(np.random.randn(2, 3), coords={'x': ['a', 'b']}, dims=('x', 'y'))
ds = xr.Dataset({'z': data})
ds.to_netcdf('netcdf_test.nc')  # works
ds.attrs['created'] = datetime.datetime.now()
ds.to_netcdf('netcdf_test_time.nc')  # fails
```

I thought about opening this issue upstream, but their solution for handling datetimes as DataArrays is precisely to use the attrs as metadata for that array. I don't think they would support generic serialization of datetimes that are *in* attrs. 

It seems like we should either not use datetimes or just serialize/deserialize ourselves.

**Comment by richardotis** [comment]
I would be comfortable converting datetimes to strings [on creation](https://github.com/pycalphad/pycalphad/blob/b6803d63107f74641f01930716f2c52d326d59d6/pycalphad/core/equilibrium.py#L359). We don't use them in any library code, from a readibility standpoint it's the same for the user, and it's trivial for downstream code to convert the string to a datetime object if programmatic access is needed. Also, it would be a one line change.
