### ISSUE TITLE
Calculate gives the wrong result if pressure and temperature are not both specified.

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#116]
In the binary example, we see the following code produce this plot 

``` python
from pycalphad import calculate
from pycalphad.plot.utils import phase_legend
import numpy as np

legend_handles, colorlist = phase_legend(my_phases_nbre)

fig = plt.figure(figsize=(9,6))
ax = fig.gca()
for name in my_phases_nbre:
    result = calculate(db_nbre, ['NB', 'RE'], name, T=2800, output='GM')
    ax.scatter(result.X.sel(component='RE'), result.GM,
               marker='.', s=5, color=colorlist[name.upper()])
ax.set_xlim((0, 1))
ax.legend(handles=legend_handles, loc='center left', bbox_to_anchor=(1, 0.6))
plt.show()
```

![image](https://user-images.githubusercontent.com/7681751/28926636-642598d2-7836-11e7-9e6a-d434cae7abbd.png)

But changing the temperature to 300 or 1000000 gives the same plot (and the same values from calculate). If you specify pressure in calculate e.g. `result = calculate(db_nbre, ['NB', 'RE'], name, T=2800, P=101325, output='GM')` the resulting plot is
![image](https://user-images.githubusercontent.com/7681751/28926687-8666f7a6-7836-11e7-925f-739b60c8274a.png)

Further changes to temperature produce expected results. The energy surface plotted when P is not specified gives a similar result to T>=6000 (piecewise max in TDB). I assume this is a bug and not the intended result?

**Comment by amjokisaari** [comment]
Please make this throw an error if something isn't specified, instead of silently calculating the wrong thing, as suggested by @richardotis.

**Comment by richardotis** [comment]
In https://github.com/pycalphad/pycalphad/blob/develop/pycalphad/core/calculate.py#L428
The assigned values to `statevar_dict` need to be wrapped with a call to `unpack_condition()`
That should fix it.

**Comment by richardotis** [comment]
That does not fix the issue. Still investigating.
