### ISSUE TITLE
Clean up pre-ESPEI code

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#121]
- [x] Remove `fitting` module which is obsolete.
- [x] Coordinate moving refdata to ESPEI. (?)

**Comment by richardotis** [comment]
`fitting` has been dead code for a long time, remove at your convenience.

For refdata, my suggestion is to move forward with the migration, including any fixes to the data (gh-120). I don't think a deprecation path is necessary, but we could replace `pycalphad.refdata` with an ImportError telling users to install a new version of ESPEI. That would make it easier to debug issues.
