### ISSUE TITLE
Update examples on pycalphad.org

### ISSUE THREAD

**Issue by amjokisaari** [pycalphad/pycalphad#127]
There are several updates for the examples on pycalphad.org that could be done:

- Non-stable or non-present phases are no longer included in legends (this is good, but the graphs don't match any more with output from v.0.5.2, e.g., Al-Fe, Al-Ni, Nb-Re plots in the binary phase diagrams section).

- Add additional information as to why Al-Ni is a "work in progress"...?

- The cementite example is missing the update from issue #99 , also make sure it includes the import numpy as np statement.

- The explanation of the pycalphad syntax is a bit out of place in the Al-Fe (degree of ordering) example.  It would be nice if it were included earlier.

- An explanation of what are all the fields / data structures shown by the "print(eq)" call in the Al-Fe (degree of ordering) example would be nice.  It's a bit confusing as it stands.

- The outputs for the "print(eq)" statements for Al-Fe, Al-Ni are out of date, v.0.2, and differ from the v0.5.2 output.

- I think the Al-Ni example (degree of ordering) is missing a plt.show() line for the phase fraction vs T plot.

- The last plot in the Al-Ni example (degree of ordering) is mis-titled as Al-Fe.

- Does v0.5.2 include ternary support?  If so, that example should be added (I believe it exists in the develop version now).

- In the examples where there are warnings (either shown in the example documentation, or not...), I think it would be a good idea to explain what these warnings are and why they occur.

**Comment by bocklund** [comment]
Thanks for these. Ternary examples are indeed in 5.2 and there's an example on the website, but it seems to not have made it into a toctree. https://pycalphad.org/docs/latest/examples/TernaryExamples.html

**Comment by amjokisaari** [comment]
Thanks!

**Comment by bocklund** [comment]
All good points.

@richardotis What do you think about having a CI script to run all the examples then convert and commit? Maybe only on tagged commits? Or maybe only on the doc branch? This would help having to keep the docs in sync with example notebooks and make sure the figures are always up to date with the expected output (e.g. when visualization options change). Relevant command and page: `jupyter nbconvert --execute --to notebook --inplace <notebook>` and [notebook docs](http://nbconvert.readthedocs.io/en/latest/execute_api.html).

**Comment by richardotis** [comment]
I think the easiest approach would be to use `nbconvert` inside the doc deployment script (the one that builds the docs) to keep the ipynb synchronized with the corresponding RST file.
