### ISSUE TITLE
Graphs are sometimes cut off when saved

### ISSUE THREAD

**Issue by amjokisaari** [pycalphad/pycalphad#128]
The right-hand information (like a legend) or the bottom axis title is sometimes cut off when saving the figure to a png.  Saving as an svg seems to include the information so that it can be moved/edited, but that's not ideal.

**Comment by bocklund** [comment]
Looks like [this SO answer](https://stackoverflow.com/a/25344713/5106932) might provide some insight. Basically in `plt.savefig` use the `bbox_extra_artists` and `bbox_inches='tight'` arguments. Not clear if we can do this automatically, but it's a starting point.

**Comment by amjokisaari** [comment]
Thanks for this.  With Python 2.7.13 and pycalphad 0.5.2, all I need to do is add the bbox_inches='tight' to the savefig command.

**Comment by bocklund** [comment]
I think the only options for enforcing this would be to patch the figure object so that the `bbox_inches='tight'` argument is automatically applied. Since that's not very predictable behavior, the upcoming documentation updates will have some kind of troubleshooting/faq page with this in it.

**Comment by richardotis** [comment]
Is it possible to modify the matplotlib options in a supported way via some global settings object?

**Comment by bocklund** [comment]
Yeah you can technically use the [matplotlib rc](https://matplotlib.org/users/customizing.html):

```
import matplotlib as mpl
mpl.rcParams['savefig.bbox'] = 'tight'
```

The question is whether we *should* do this or not.

**Comment by richardotis** [comment]
How about check the value and warn the user if it isn't set?

**Comment by bocklund** [comment]
On import? I think import spam is kind of annoying

**Comment by bocklund** [comment]
Hard to anticipate if users will be using `savefig`. If they aren't we probably don't want to warn them

**Comment by richardotis** [comment]
I mean, inside eqplot is it possible?

**Comment by bocklund** [comment]
We could warn inside eqplot, but I'm thinking that I call savefig only a small fraction of the time I use eqplot because I work in the notebook so often.

**Comment by amjokisaari** [comment]
Maybe it's not worth trying to fix, but add it into documentation somewhere?  ("Exporting figures" section?)
