### ISSUE TITLE
Python 2 causes generation of wrong graph axis labels

### ISSUE THREAD

**Issue by amjokisaari** [pycalphad/pycalphad#132]
Graph x-axis labels are not generated properly using Python 2.7 (work as expected with Python 3.6), such that the wrong element can be supplied to the label for a phase diagram.  See attached image; that x-axis should read "X(AL)".

@bocklund pointed out [this code](https://github.com/pycalphad/pycalphad/blob/develop/pycalphad/plot/eqplot.py#L173) as the [probable cuplrit](https://stackoverflow.com/a/4199355/5106932), though really that's bad behavior in Python 2.

![alzn_py27_bug](https://user-images.githubusercontent.com/6676372/30869252-487cb116-a2a6-11e7-9b43-081ccf1f472c.png)

**Comment by bocklund** [comment]
Yeah it's actually odd if you continue reading the comments that set and dict comprehensions do not leak, but only lists!
