### ISSUE TITLE
Document the pycalphad xarray datasets

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#134]

**Comment by richardotis** [comment]
Closest attempt at it so far: https://openresearchsoftware.metajnl.com/articles/10.5334/jors.140/#F3

**Comment by amjokisaari** [comment]
It's definitely helpful (I've been referring to the paper, etc before
asking questions) but it's not complete.  The biggest thing missing here
(for me as a newbie to the project) is that "X" and "Y" are not also
described there.
