### ISSUE TITLE
About scheil simulation module

### ISSUE THREAD

**Issue by yangshenglan** [pycalphad/pycalphad#138]
Dear Richard, I would like to ask whether there are Scheil simualtion module or not in pycalphad.

**Comment by richardotis** [comment]
There is no built-in support for Scheil simulation currently, but since you can use pycalphad to compute equilibrium at any temperature and composition, it is possible to apply the Scheil equation over a temperature range and compute the liquid and solid fractions.

**Comment by richardotis** [comment]
@yangshenglan I put together a short sketch of the Scheil calculation code here: https://notebooks.azure.com/rotis/libraries/scheilsketch

If you run the notebook on Azure, give it a minute or so to install pycalphad before the calculation completes.

I didn't have a nice multi-component alloy database to show the idea off nicely, so if you have something in particular you'd like to do, I'd be happy to discuss it further with you.

**Comment by yangshenglan** [comment]
Thank you for your reply and suggestion！

**Comment by richardotis** [comment]
Just a note for @yangshenglan and others who come across this: I've been discussing Scheil solidification with @bocklund, and he pointed out the example code I posted has a few bugs which will cause the wrong answer to be given, so please look at it more as a rough idea of how you might do an iterative series of calculations.

We would like to have working Scheil solidification modeling for pycalphad, but we are both pretty slammed with other development tasks currently. If you have a use case for this (neither of us do at the moment), please contact us and we can increase the priority of this feature.
