### ISSUE TITLE
Update install docs to use one line conda installation

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#153]
`conda install pycalphad -c pycalphad -c msys2 -c conda-forge`

They are searched in order per [conda install docs](https://conda.io/docs/commands/conda-install.html). Prioritize pycalphad > msys2 > conda-forge > conda and mention the sorting

**Comment by yangshenglan** [comment]
Hi, Bocklund! I have a question and ask for your help.  @bocklund 
I use the .tdb file ('NI_AL_DUPIN_2001.TDB') provided examples of pycalphad to calculate thermodynamic equilibrium in the following link.
https://pycalphad.org/docs/latest/examples/BinaryExamples.html#calculating-energy-surfaces-of-binary-systems
Also, the codes are shown as 
`eq_result = equilibrium(db, ['AL', 'NI'], ['FCC_A1', 'LIQUID'], {v.X('NI'): 0.01, v.T: 918, v.P: 101325})`
`eq_result = equilibrium(db, ['AL', 'NI'], ['FCC_A1', 'LIQUID'], {v.X('NI'): 0.01, v.T: 918, v.P: 101325}, calc_opts={'pdens':10000})`
Unfortunately, two-phase equilbrium of FCC_A1 and LIQUID can't be calculated. The result shows that there is only LIQUID phase in this equilibrium. In fact, there is a focus of the  two Gibbs energy curves for FCC_A1 and LIQUID phases and there is two-phase equilibrium of FCC_A1 and LIQUID phases at 918K and the mole fraction of Ni with 0 to 0.03(shown as the following figure which is plotted by pycalphad). 
![918_fcc_a1_liquid](https://user-images.githubusercontent.com/17959520/36899155-cc3fae3a-1e58-11e8-93f8-1643cf6d4985.png)
Also, the phase diagram calculated by pycalphad is as following. But the phase diagram is wrong, for example,  the eutectic reaction at Al-rich coner isn't calculated.
![alni2001_xni](https://user-images.githubusercontent.com/17959520/36899377-c5b9eb56-1e59-11e8-839e-1d6baab3b93b.png)
The following phase diagram is calculated by Thermo-Calc Software.
![nial_dupin_2001](https://user-images.githubusercontent.com/17959520/36899512-644ca13c-1e5a-11e8-8a48-74bcc1b6e895.png)
Enlarged drawings for two region of the red circle in the above figure are as following
![nial_dupin_2001_1](https://user-images.githubusercontent.com/17959520/36899652-0db56b32-1e5b-11e8-865b-dfdc92c33e30.png)
![Uploading NiAl_Dupin_2001_2.png…]()

**Comment by bocklund** [comment]
What version of pycalphad are you using?

**Comment by yangshenglan** [comment]
using pycalphad 0.6.1

**Comment by bocklund** [comment]
From a quick look, it looks like you have two issues. First is not including vacancies (`'VA'`) in your components, second is that the AL-NI system is modeled using an FCC_A1-FCC_L12 order disorder and by using `phases = ['FCC_A1', 'LIQUID']` you are not using the order-visored FCC_L12 phase.

The correct point calculation, I believe is 

`equilibrium(db_alni, ['AL', 'NI', 'VA'], ['FCC_L12', 'LIQUID'], {v.X('NI'): 0.01, v.T: 918, v.P: 101325})`

which gives me output:


```
<xarray.Dataset>
Dimensions:    (P: 1, T: 1, X_NI: 1, component: 2, internal_dof: 5, vertex: 2)
Coordinates:
  * P          (P) float64 1.013e+05
  * T          (T) float64 918.0
  * X_NI       (X_NI) float64 0.01
  * vertex     (vertex) int64 0 1
  * component  (component) <U2 'AL' 'NI'
Dimensions without coordinates: internal_dof
Data variables:
    NP         (P, T, X_NI, vertex) float64 0.6437 0.3563
    GM         (P, T, X_NI) float64 -3.847e+04
    MU         (P, T, X_NI, component) float64 -3.694e+04 -1.898e+05
    X          (P, T, X_NI, vertex, component) float64 0.998 0.001982 0.9755 ...
    Y          (P, T, X_NI, vertex, internal_dof) float64 0.998 0.001982 ...
    Phase      (P, T, X_NI, vertex) <U7 'FCC_L12' 'LIQUID'
Attributes:
    engine:   pycalphad 0.6.1+58.g29fedc0d
    created:  2018-03-02T13:31:12.331059
```

**Comment by yangshenglan** [comment]
My intention is calculating two-phase equilibrium of FCC_A1 and LIQUID phases instead of FCC_L12 and LIQUID phases. It gets two different results calculating two-phase equilibrium of FCC_A1 and LIQUID phases using two .tdb files including information of FCC_L12 and not including it. What's reason of this?

**Comment by bocklund** [comment]
If you are using Dupin’s database in Thermo-Calc as you downloaded it from pycalphad, then you are including the energy from the L12 order-disorder contribution and TC is labeling the phase FCC_A1 because it is detecting that the sublattices are disordered. In pycalphad, using the phase `FCC_L12` is required in the order disorder to get the right energies regardless of whether the final phase is the ordered L12 or disordered A1. Does that make sense?

If that is still unclear, could you be more specific on what exactly you are calculating? Can you share the other database with me? Giving example pycalphad code and a Thermo-Calc macro that you expect to give the same answer for a point calculation would be really helpful.

**Comment by bocklund** [comment]
To further clarify my point in the first paragraph: if you do the same point calculation as I did (with FCC_L12) you should find that the site fractions (`Y`) in the calculation result are the same in the FCC_L12 sublattices, meaning we found that the equilibrium phase is disordered.

**Comment by yangshenglan** [comment]
I've got it. Thank you for your help.
