### ISSUE TITLE
Improve JIT compilation time with symengine

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#155]
Compilation of order-disorder models is particularly slow.

Using symengine would possibly enable a large speedup in compilation time https://github.com/symengine/symengine/issues/1038

As part of this, we might have to come up with a solution to profile the compilation steps.

**Comment by richardotis** [comment]
An estimate from profiling `test_eq_ternary_inside_mass` suggests (after merging #156) that differentiation and code printing is about 20% of the total execution time for a point calculation.

**Comment by bocklund** [comment]
That's acceptable to me. Should we close this with #156 until we find a case where compiling is expensive? Without a test case, I don't see a compelling reason to investigate pulling in another dependency.

**Comment by richardotis** [comment]
Agreed.
