### ISSUE TITLE
pycalphad 0.7 Windows AttributeErrors 

### ISSUE THREAD

**Issue by aliua** [pycalphad/pycalphad#167]
After downloading the pycalphad 0.7, using this scripts and B-Mg.tdb database, I got the following errors.

```
import matplotlib.pyplot as plt
from pycalphad import Database, binplot
import pycalphad.variables as v

db_b_mg = Database('B-Mg.tdb')
my_phases_b_mg = ['GAS', 'LIQUID', 'BETA_RHOMBO_B', 'HCP_A3', 'MGB2', 'MGB4', 'MGB7']
fig = plt.figure(figsize=(9,6))
binplot(db_b_mg, ['B', 'MG', 'VA'] , my_phases_b_mg, {v.X('B'):(0,1,0.05), v.T: (300, 4300, 20), v.P:101325},  ax=fig.gca())
plt.xlim((0,1))
plt.show() 
```

```
 runfile('C:/Users/student/Desktop/Pycalphad/pycalphad_binplot_Mg-B.py', wdir='C:/Users/student/Desktop/Pycalphad')
Traceback (most recent call last):

  File "<ipython-input-4-5a2237aca5f4>", line 1, in <module>
    runfile('C:/Users/student/Desktop/Pycalphad/pycalphad_binplot_Mg-B.py', wdir='C:/Users/student/Desktop/Pycalphad')

  File "C:\Users\student\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\student\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/student/Desktop/Pycalphad/pycalphad_binplot_Mg-B.py", line 2, in <module>
    from pycalphad import Database, binplot

  File "C:\Users\student\Anaconda3\lib\site-packages\pycalphad\__init__.py", line 25, in <module>
    import pycalphad.variables as v

AttributeError: module 'pycalphad' has no attribute 'variables'
```
-------
edited by @bocklund to reformat traceback into code block

**Comment by richardotis** [comment]
Do you have a folder called "pycalphad" somewhere in your working directory? Your Python may be getting confused. I would try renaming it.

**Comment by aliua** [comment]
Yes, I have a folder name pycalphad and I have changed it, Now I have found this new error.

 

> runfile('C:/Users/student/Desktop/pcal/pycalphad_binplot_Mg-B.py', wdir='C:/Users/student/Desktop/pcal')
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-ac90f25cb2f9>", line 1, in <module>
>     runfile('C:/Users/student/Desktop/pcal/pycalphad_binplot_Mg-B.py', wdir='C:/Users/student/Desktop/pcal')
> 
>   File "C:\Users\student\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\student\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/student/Desktop/pcal/pycalphad_binplot_Mg-B.py", line 2, in <module>
>     from pycalphad import Database, binplot
> 
>   File "C:\Users\student\Anaconda3\lib\site-packages\pycalphad\__init__.py", line 32, in <module>
>     from pycalphad.core.calculate import calculate
> 
>   File "C:\Users\student\Anaconda3\lib\site-packages\pycalphad\core\calculate.py", line 9, in <module>
>     from pycalphad.core.sympydiff_utils import build_functions
> 
>   File "C:\Users\student\Anaconda3\lib\site-packages\pycalphad\core\sympydiff_utils.py", line 4, in <module>
>     from .custom_autowrap import autowrap, import_extension
> 
>   File "C:\Users\student\Anaconda3\lib\site-packages\pycalphad\core\custom_autowrap.py", line 76, in <module>
>     from sympy.codegen.ast import Assignment
> 
> ModuleNotFoundError: No module named 'sympy.codegen'
> 
>

**Comment by richardotis** [comment]
Your version of sympy may be too old. Try updating it to the latest version.

**Comment by aliua** [comment]
Got it
![image](https://user-images.githubusercontent.com/37589112/37684428-02a99e28-2c5e-11e8-9bda-a72f86b545b3.png)
!

**Comment by aliua** [comment]
Now the challenge is to add the experimental excess energy to this system.

**Comment by richardotis** [comment]
Do you know which phase you want to add energy to?

**Comment by aliua** [comment]
I want to add excess Gibbs energy of mixing (X_B= 0.07 ,0.6, 0.73,0.84, 0.95), this composition.

**Comment by aliua** [comment]
```
import matplotlib.pyplot as plt
from pycalphad import Database, binplot , calculate
from pycalphad.plot.utils import phase_legend
import pycalphad.variables as v
import numpy as np
db_b_mg = Database('B-Mg.tdb')
my_phases_b_mg = ['GAS', 'LIQUID', 'BETA_RHOMBO_B', 'HCP_A3', 'MGB2', 'MGB4', 'MGB7']
fig = plt.figure(figsize=(9,6))
binplot(db_b_mg, ['B', 'MG', 'VA'] , my_phases_b_mg, {v.X('B'):(0,1,0.05), v.T: (300, 4300,20), v.P:101325},tielines=False,  ax=fig.gca())
plt.xlim((0,1))
plt.show()

legend_handles, colorlist = phase_legend(my_phases_b_mg)

fig = plt.figure(figsize=(9,6))
ax = fig.gca()

for name in my_phases_b_mg:
    result = calculate(db_b_mg, ['B', 'MG'], name, P=101325, T=1000, output='GM')
    ax.scatter(result.X.sel(component='MG'), result.GM,
               marker='.', s=6, color=colorlist[name.upper()])
ax.set_xlim((0, 1))
ax.legend(handles=legend_handles, loc='center left', bbox_to_anchor=(1, 0.6))
plt.show()
```
Errors:
![image](https://user-images.githubusercontent.com/37589112/37687225-b390a5c4-2c68-11e8-8248-fd06e59a01e0.png)

C:\Users\student\Anaconda3\lib\site-packages\pycalphad\core\calculate.py:344: UserWarning: Suspending specified phase HCP_A3 due to
                some sublattices containing only unspecified components
  some sublattices containing only unspecified components""".format(phase_name))
Traceback (most recent call last):

  File "<ipython-input-24-250965b4c187>", line 1, in <module>
    runfile('C:/Users/student/Desktop/pcal/pcal_binplot_Mg-B.py', wdir='C:/Users/student/Desktop/pcal')

  File "C:\Users\student\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\student\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/student/Desktop/pcal/pcal_binplot_Mg-B.py", line 19, in <module>
    result = calculate(db_b_mg, ['B', 'MG'], name, P=101325, T=1000, output='GM')

  File "C:\Users\student\Anaconda3\lib\site-packages\pycalphad\core\calculate.py", line 413, in calculate
    final_ds = all_phase_data[0]

IndexError: list index out of range
![image](https://user-images.githubusercontent.com/37589112/37687231-b9f96306-2c68-11e8-9267-c676a164a2f2.png)

**Comment by richardotis** [comment]
Do you know the value of L_MgB you want to use?

**Comment by aliua** [comment]
![image](https://user-images.githubusercontent.com/37589112/37693191-0b97024a-2c8c-11e8-8ce9-6687e87eda3b.png)

I have Gex value for Mg-B binary solution:
![image](https://user-images.githubusercontent.com/37589112/37693223-38255f78-2c8c-11e8-8b4b-335e6044a43a.png)

For an example:
![image](https://user-images.githubusercontent.com/37589112/37693245-53b0a19e-2c8c-11e8-9c18-9a831c6fa093.png)

**Comment by bocklund** [comment]
For the Ag-Cu example in the email (below), those excess parameters would be entered directly into a TDB as the following (Assuming the liquid sublattice model is `(AG,CU)`)


![37693245-53b0a19e-2c8c-11e8-9c18-9a831c6fa093](https://user-images.githubusercontent.com/7681751/37709504-c9b9c790-2ce0-11e8-8879-b8122c9607f6.png)


```
PARAMETER L(LIQUID,AG,CU;0) 298.15    17384.4 - 4.46430*T; 10000 N !
PARAMETER L(LIQUID,AG,CU;1) 298.15    1660.8 - 2.31510*T; 10000 N !
```

e.g., the following format:`L(phase_name,A,B;i` where  `i`  is the order of the excess parameter and the others are more or less self explanatory. The 298.15 and 10000 are the lower and upper temperature bounds of that parameter in Kelvin.

**Comment by aliua** [comment]
No change after adding the Parameter!!
 ![image](https://user-images.githubusercontent.com/37589112/37730814-9c150880-2d0e-11e8-9dfd-9d4a1ca82fe8.png)

**Comment by bocklund** [comment]
Can you share the TDB? Are you using the same script? 


Thank you,
Brandon Bocklund

**Comment by aliua** [comment]
Yes, I am using the same script. In TDB, I have just added this two lines, 
```
PARAMETER G(MG,B;0) 298.15    -xxxx - xxx*T; 3000 N !
PARAMETER G(MG,B;1) 298.15    -xxxx - xxx*T; 3000 N !
```

**Comment by bocklund** [comment]
Needs to be 

> PARAMETER G(LIQUID,MG,B;0) 298.15 -xxxx - xxx*T; 3000 N !
You have to specify which phase. Otherwise it should work. 

Thank you,
Brandon Bocklund

**Comment by aliua** [comment]
Thanks! its works, 
BTW, how to put the lines on(like thermocalc fig attached), in the binplot.
![image](https://user-images.githubusercontent.com/37589112/37736950-53171de6-2d20-11e8-8aa7-0f51d0276b7f.png)

**Comment by bocklund** [comment]
pycalphad currently cannot plot invariant lines automatically because of the (naîve) way that we calculate phase diagrams. It's definitely on our todo list and is a highly requested feature.

**Comment by bocklund** [comment]
@aliua is this ok to close? I'll take no response as a yes. 

Feel free to open another issue or [talk to us on Gitter](https://gitter.im/pycalphad/pycalphad) if you have any more questions.

**Comment by aliua** [comment]
Yes ok to close.

Ali
