### ISSUE TITLE
changing constants in equilibrium calculation without reinstaling

### ISSUE THREAD

**Issue by broshe** [pycalphad/pycalphad#174]
In the past (version 0.5) it was not possible to change constants such as 
MAX_SOLVE_DRIVING_FORCE  without reinstalling pycalphad.
Now, I find that there is a constants.py module that contains several constants.
I tried to run at the head of my program:
import pycalphad.core.constants
pycalphad.core.constants.MIN_SITE_FRACTION = 1e-14
pycalphad.core.constants.MIN_PHASE_FRACTION = 1e-7
pycalphad.core.constants.COMP_DIFFERENCE_TOL = 1e-6
pycalphad.core.constants.MAX_SOLVE_DRIVING_FORCE = 1e-6
pycalphad.core.constants.MAX_SOLVE_ITERATIONS = 4000
pycalphad.core.constants.MIN_SOLVE_ENERGY_PROGRESS = 1e-6

but could not see a change in the performance.
Is this the correct method of changing constants?
Can it now be done without reinstalling pycalphad?

Best regards,
Eli

**Comment by richardotis** [comment]
Hi Eli, in recent versions of pycalphad (0.7.x) the equilibrium solver has been rewritten and uses a new solver code, so this code will no longer work. The new solver is much more robust and it should be unnecessary to alter the convergence constants.

**Comment by bocklund** [comment]
@richardotis some of these are still used outside the solver (e.g. MIN_SITE_FRACTION) and we should keep them IMO.

But others are still meaningful, e.g. `MAX_SOLVE_ITERATIONS` even though we are using ipopt now.  Should we remove them as dead code or allow them to be passed through to `solver.py` where they are hardcoded (`nlp.addOption(b'max_iter', 200)`)?

I'm happy to clean these up and pass relevant options through if that's what we want to do. IMO it's worth doing.

**Comment by richardotis** [comment]
The future will be to construct custom `Solver` objects to pass to `equilibrium`. We should limit mutating global state as much as possible.

**Comment by bocklund** [comment]
So the initializer should take keyword arguments with defaults?


Thank you,
Brandon Bocklund

**Comment by richardotis** [comment]
My preference is for subclasses of `Solver` to override the `solve` method (and perhaps also `__init__`) and configure any specific options there. I don't want any solver state to leak outside of that class because it would mean committing to support particular solver configuration options in the future, which may or may not be available, or may mean different things in different packages.

User-developed custom `Solver` subclasses can have any signature they want, of course, depending on what makes sense for their work. I think the configuration API for the builtin `Solver` should be very limited, to avoid users hard-coding solver constants for an optimization package which is subject to change in the future.

**Comment by bocklund** [comment]
I have this in a branch. Will push and open a PR in a bit


Thank you,
Brandon Bocklund

**Comment by bocklund** [comment]
Hi Eli,

As Richard said before, the solver is much more robust and you should not need to change it. 

However, if you are still interested in tinkering, you can instantiate a `pycalphad.solver.InteriorPointSolver` with any IPOPT options you like (IPOPT is the local min solver; see https://www.coin-or.org/Ipopt/documentation/node40.html for the options).

You can then pass that object to the `solver` keyword argument of `equilibrium`. 

For example,

```python
from pycalphad import equilibrium, Database, variables as v
from pycalphad.core.solver import InteriorPointSolver

# normal setup
dbf = Database('CU-MG.tdb')
comps = ['CU', 'MG', 'VA']
phases = list(dbf.phases.keys())
conds = {v.P: 101325, v.T: 300, v.X('MG'): 0.5}

# instantiate a solver
my_solver = InteriorPointSolver(max_iter=4000, tol=1e-4)
eq_result = equilibrium(dbf, comps, phases, conds, solver=my_solver)```

**Comment by broshe** [comment]
Hi Brandon.
Is this feature already in pycalphad 0.7 or is it to appear in 0.71 ?

Regards,
Eli

On Tue, Jun 19, 2018 at 12:05 AM, Brandon Bocklund <notifications@github.com
