### ISSUE TITLE
trace and debug from python code going into cython code?

### ISSUE THREAD

**Issue by superjery** [pycalphad/pycalphad#181]
how to debug cython and python code togethor, especial how to trace and dig into cython code?

**Comment by superjery** [comment]
Second question: Why not convert lower_convex_hull.py to cython code? because it's taking too much time in there.

**Comment by superjery** [comment]
I'm waiting for good news! Thank you.

**Comment by richardotis** [comment]
Using standard tools like cProfile and snakeviz work fine with Cython code compiled with `# cython: profile=True` at the top of the module. See here: https://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html

`lower_convex_hull.py` is in the process of being partially rewritten in the `advanced-conditions` branch, but the really hot part of it is already written in Cython, see `hyperplane.pyx`.

**Comment by superjery** [comment]
Thank you for replying. 
I'm newer for cython. But I can feel cython is powerfull.
And I want to make breakpoints and debug cython step by step, just like debug python code in IDE(like eclipse+pydev).
Now debug python is not big deal, but when I make a breakpoint in cython and python code, and the IDE will stop in python code breakpoint and skip cython code breakpoint, 
So  how you make breakpoints and debug both cython and python code together?
This is very important to me! (because i'm adding quasi-chemical model in code, must go through this)

**Comment by superjery** [comment]
Thanks
Well，it's nightmare to debug cython, How you  guys to debug cython.

**Comment by superjery** [comment]
Thanks
Well，it's nightmare to debug cython, How you guys to debug cython？

**Comment by superjery** [comment]
Thanks
Well，it's nightmare to debug cython, How you guys to debug cython?

**Comment by richardotis** [comment]
We agree that it's not easy. We've shared with you the tools we use, if you're looking for alternatives we recommend posting a question on StackOverflow using the cython tag. That way many more developers will see your question than read the posts on pycalphad's issue tracker.
