### ISSUE TITLE
I couldn't find any module that calls the compiled_model.pyx?

### ISSUE THREAD

**Issue by superjery** [pycalphad/pycalphad#183]
Functions are build by build_functions in sympydiff_utils. So Which module calls the compiled_model.pyx?

**Comment by richardotis** [comment]
compiled_model.pyx is old code that will be removed in the next version.

**Comment by superjery** [comment]
Thanks

**Comment by superjery** [comment]
So What's the reason to remove it?
Is it not big difference of the calling time of  build_functions and compiled_model.pyx ? so turn back to use build_functions and drop compiled_model.pyx ?

**Comment by richardotis** [comment]
Yes, you are correct. It's a lot of work to maintain Model and CompiledModel together, for little benefit, so CompiledModel will be removed.

**Comment by superjery** [comment]
Thanks. I see.
As I read the project, find out that the whole project is awesome.
So I'm thinking that the last phasediagram picture should be plotted with lines like in TC and Pandat, should not be plotted with dashed area? Any plan on that?

**Comment by superjery** [comment]
As binary phasediagram, three phase region with zero freedom is not exactly calculated, which the tempareture of three phase region is not exactly caclulated as the problem only taking composition into consideration with given temparature. Any plan on that?

**Comment by richardotis** [comment]
Yes, we are working on a new system for conditions which will allow more flexibility. You can track its progress in the `advanced-conditions` branch.

**Comment by superjery** [comment]
Yes, in advanced-conditions branch, I could find that multiphase_constraint is based on the condition "cur_conds = properties['GM'].coords".  Does the condition "cur_conds = properties['GM'].coords" deal with threee phase with zero freeedom conditon? I can't get the clue.

**Comment by richardotis** [comment]
That part isn't implemented yet.

**Comment by superjery** [comment]
Ok. Thanks.
