### ISSUE TITLE
Some doubt on pycalphad/core/solver.py?

### ISSUE THREAD

**Issue by superjery** [pycalphad/pycalphad#190]
In advanced-condition branch and in pycalphad/core/solver.py line 169 and 170 ad below
chemical_potentials = np.linalg.lstsq(mu_jacobian.T,
                                              prob.gradient(x) - info['mult_x_L'] - info['mult_x_U'])

I think the above should be 
chemical_potentials = np.linalg.lstsq(mu_jacobian.T,
                                              prob.gradient(x) - info['mult_x_L'] + info['mult_x_U'])

For moust cases, the lower and uper bound multiiplyer are zero, but I think the sign should be one negtive(lower bound) and one positive(uper bound)?

**Comment by richardotis** [comment]
You are correct that the signs of the multipliers are opposite, but when you distribute the subtraction operation they will both be negative.

**Comment by superjery** [comment]
Thank you.
Well I have another question:
https://i.postimg.cc/dtGfsM3Q/IMG-20181023-163658.jpg
I think the above is the equation solved。Am I right？
So what is real eqation solved?

**Comment by richardotis** [comment]
We're applying the condition that the gradient of the Lagrangian should be zero at the solution (which we already know, in this part of the code), which means that the product of the constraint Jacobian matrix with the Lagrange multipliers (e.g., chemical potentials) should equal the negative of the objective function gradient. We set that up as a linear system of equations and solve for the Lagrange multipliers. There are more details in Chapter 18 of Nocedal and Wright's Numerical Linear Algebra textbook.

**Comment by superjery** [comment]
Thank you for reply again!
Well question again:
https://i.postimg.cc/bvNGfpB2/IMG-20181024-093149.jpg
(1) AkT should be prob.mass_gradient(x).T , but equation (18.10) use -AkT (negtive). Should there be negtive sign? Does I miss something?
(2) info['mult_g'] contain Lagrange multipliers (e.g., chemical potentials), I think these potentials are sub-lattice species potentials. The equation pycalphad solver used is solved for pure elements? Am i right?

**Comment by superjery** [comment]
Well I get new thought:
https://i.postimg.cc/sXKQDRmb/IMG-20181024-135736.jpg
We just ignore and drop  the -pk part, and this will lead to the equation solver used.
For the question (1), Am I right?

**Comment by richardotis** [comment]
You have the idea. That part drops out because we're at the solution already (in this case), so the step size is zero.

For your second question, by construction, these are all the Lagrange multipliers for the mass balance of the pure elements, so they are chemical potentials.

**Comment by superjery** [comment]
Thank you.
I get it.
