### ISSUE TITLE
Windows release 0.7.1.post2

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#199]
Looks like we aren't currently building for Windows on conda forge, so we either need to address that or upload a manually built package to the pycalphad channel

**Comment by bocklund** [comment]
I'm in favor of packaging Windows (or all platforms) on the pycalphad channel.

**Comment by bocklund** [comment]
Since the 0.8 release is coming soon, I'm closing this since an explict 0.7.1post2 release for Windows is not planned.
