### ISSUE TITLE
Most examples not working 

### ISSUE THREAD

**Issue by Austin-J-Ross** [pycalphad/pycalphad#210]
binplot kills my kernel when running through those examples. Not quite sure why. I'm operating off the anaconda install: conda install -c pycalphad -c msys2 -c conda-forge pycalphad

The kernel also dies when using the equilibrium function.

When I try to run the Heat Capacity of Cementite ( 𝐹𝑒3𝐶 ) I encounter the following error when I run calculate:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-6154fa33d9d7> in <module>
----> 1 result = calculate(db, ['FE', 'C'], 'CEMENTITE_D011', T=(1, 2000, 0.5), output='heat_capacity')

C:\ProgramData\Anaconda3\lib\site-packages\pycalphad\core\calculate.py in calculate(dbf, comps, phases, mode, output, fake_points, broadcast, parameters, **kwargs)
    390         phase_record = PhaseRecord_from_cython(comps, list(statevar_dict.keys()) + variables,
    391                                     np.array(dbf.phases[phase_name].sublattices, dtype=np.float),
--> 392                                     param_values, comp_sets[phase_name], None, None, mass_dict[phase_name], None)
    393         points = points_dict[phase_name]
    394         if points is None:

pycalphad\core\phase_rec.pyx in pycalphad.core.phase_rec.PhaseRecord_from_cython()

pycalphad\core\phase_rec.pyx in pycalphad.core.phase_rec.PhaseRecord_from_cython()

C:\ProgramData\Anaconda3\lib\site-packages\pycalphad\core\sympydiff_utils.py in kernel(self)
     52                                 raise
     53                 else:
---> 54                     self._kernel = self.compile()
     55         return self._kernel
     56 

C:\ProgramData\Anaconda3\lib\site-packages\pycalphad\core\sympydiff_utils.py in compile(self)
     79     def compile(self):
     80         with CompileLock:
---> 81             result, self._cpointer, self._module_name, self._routine_name = autowrap(self._sympyobj, args=self._sympyvars, backend='Cython', language='C', tempdir=self._workdir)
     82         return result
     83 

C:\ProgramData\Anaconda3\lib\site-packages\pycalphad\core\custom_autowrap.py in autowrap(expr, language, backend, tempdir, args, flags, verbose, helpers)
    726             expr = expr.subs(expr_h, name_h(*args_h))
    727     try:
--> 728         routine = make_routine('autofunc', expr, args)
    729     except CodeGenArgumentListError as e:
    730         # if all missing arguments are for pure output, we simply attach them

C:\ProgramData\Anaconda3\lib\site-packages\pycalphad\core\custom_autowrap.py in make_routine(name, expr, argument_sequence, global_vars, language)
    658     code_gen = get_code_generator(language, "nothingElseMatters")
    659 
--> 660     return code_gen.routine(name, expr, argument_sequence, global_vars)
    661 
    662 

C:\ProgramData\Anaconda3\lib\site-packages\pycalphad\core\custom_autowrap.py in routine(self, name, expr, argument_sequence, global_vars)
    392                 metadata = {}
    393 
--> 394             arg_list.append(InputArgument(symbol, **metadata))
    395 
    396         output_args.sort(key=lambda x: str(x.name))

C:\ProgramData\Anaconda3\lib\site-packages\sympy\utilities\codegen.py in __init__(self, name, datatype, dimensions, precision)
    291         """
    292         if not isinstance(name, (Symbol, MatrixSymbol)):
--> 293             raise TypeError("The first argument must be a sympy symbol.")
    294         if datatype is None:
    295             datatype = get_default_datatype(name)

TypeError: The first argument must be a sympy symbol.

**Comment by Austin-J-Ross** [comment]
Update: everything is working fine when I install the dev version. I'll continue to investigate. My installation of Anaconda is fairly new so I haven't done much to the packages...

**Comment by richardotis** [comment]
@Austin-J-Ross pycalphad 0.7.x is broken when using the latest versions of some packages. We've fixed the bugs in the development version and are working on a release next month before the annual CALPHAD meeting.

**Comment by Austin-J-Ross** [comment]
Great to hear! I look forward to using PyCalphad more.

**Comment by bocklund** [comment]
Tagging as 0.8 milestone to check that all examples are working before a release

**Comment by bocklund** [comment]
Closed by #211
