### ISSUE TITLE
Build Python wheels

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#221]
Now that a compiler toolchain is no longer a run-time dependency, it makes more sense to build Python wheels. While we will continue to recommend Anaconda packages, it may reduce friction for users in non-Anaconda environments, like Enthought or Spyder.

**Comment by richardotis** [comment]
`python setup.py bdist_wheel` in a properly-configured development environment appears to just work.

**Comment by bocklund** [comment]
conda-press could also be an option here

**Comment by richardotis** [comment]
I think we should first help upstream build wheels for `cyipopt`, since `pip install pycalphad` will not work without it.

**Comment by richardotis** [comment]
`cyipopt` is no longer a dependency as of #329, and wheels are now being built during CI as of #331. Wheels will be available starting with the release of the 0.9 series.
