### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by oliverstefanov** [pycalphad/pycalphad#227]
Hi,
I installed PyCalphad with conda on Win10, and the notebooks generally run fine.

However, when I try to execute a regular python file from the conda prompt, I get the following type of error:

ImportError: cannot import name 'Database' from 'pycalphad' 

Should I install the dev version instead?

**Comment by richardotis** [comment]
Jupyter and pycalphad may not be in the same conda environment. Can you `conda install jupyter` in the same environment you installed pycalphad in?

**Comment by oliverstefanov** [comment]
Thanks for your feedback. Jupyter was installed in the pycalphad environment. I tried a few things, it's actually working now but I'm not sure why..!
