### ISSUE TITLE
Cannot calculate the disordered phase in an order disorder model, even if it's the only active phase in the calculation

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#247]
The disordered part of a phase in an order-disorder model gets filtered out as a possible phase by `pycalphad.core.utils.filter_phases`.

This is usually the behavior we want if the ordered phase will be active, for example in the ordered FCC_L12 phase with the disordered part FCC_A1.
```python
calculate(dbf, comps, ['FCC_A1', 'FCC_L12', 'LIQUID', 'BCC_A2'], T=300.0, N=1.0, P=101325.0)
# active phases in calculation: ['FCC_L12', 'LIQUID', 'BCC_A2'] (correct)
```
the FCC_A1 phase is made inactive in favor of the FCC_L12. However, if the ordered part is not passed in the list of phases to consider, we should allow the disordered part to be active, e.g.
```python
calculate(dbf, comps, ['FCC_A1', 'LIQUID', 'BCC_A2'], T=300.0, N=1.0, P=101325.0)
# active phases in calculate: ['LIQUID', 'BCC_A2'] (current)
# active phases in calculate: ['FCC_A1', 'LIQUID', 'BCC_A2'] (correct)
```
would use the disordered FCC_A1 phase and not the ordered FCC_L12 phase. And further, 
```python
calculate(dbf, comps, 'FCC_A1', T=300.0, N=1.0, P=101325.0)
# active phases in calculate: [] (current)
# active phases in calculate: ['FCC_A1'] (correct)

```
should work, but it currently does not (raises with the error that no phases are active).

**Comment by igorjrd** [comment]
Seems like is a problem due `pycalphad.core.utils.filter_phases()` structure. `filter_phases()` is currently taking the dbf and the comps to check if the sublattices are active and, if the dbf contains simultaneously both ordered and ordered phases definition, the disordered phase model is not returned by this function. Maybe we can refactor filter_phases() to take `phases` as arg and check if the ordered phases of each phase is present in the `phases` argument.
