### ISSUE TITLE
The io subpackage should be renamed because it shadows a builtin module

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#253]

**Comment by bocklund** [comment]
With 0.9, we can have some backwards compatible change, so it's safe to break this now. The question is what to rename it to, or whether there's a better way to organize.

- SciPy still has an `io` module and I can't find an issue about changing it. Maybe they aren't planning to change it?
- NumPy changed their `io` module to `npyio`

Some ideas for names of the subpackage

- `io_` - the least intrusive and maintains correctness and the concept
- `databases` - may be misleading to think that there are TDB files or something in the subpackage
- `database_io` - I like that it's more specific. This may be my favorite.
- `backends` - e.g. matplotlib or xarray
- `storage` or `storages` - e.g. TinyDB
- `serialization`
- `parsing`

**Comment by richardotis** [comment]
Is this Python issue an accurate description of why this change should be made? https://bugs.python.org/issue32845
It isn't clear to me how our users could ever run into this issue due to `pycalphad.io`.

**Comment by bocklund** [comment]
That’s basically the idea. Since python 3, the io module has been a built-in. 

For users, it’s not that big of a deal, since it’s always namespaced under pycalphad. For developers it can be an issue if the CWD is inside the main package, then `from io` imports the pycalphad sub package instead of the built-in. Developers also need to be careful when doing imports from the io sub package to either use fully qualified (`from pycalphad.io import foo`) imports or relative imports (`from .io import foo`) .

I think I opened this issue because I ran into that once. It actually wouldn’t be a big deal to me to close it as long as the issue were here if anyone were to make the same mistake later.

**Comment by richardotis** [comment]
`from pycalphad import io` is not good practice for reasons mentioned above, but I also don't see it as a likely case: `pycalphad/io/__init__.py` is empty today, so no names are exposed at that level. At the very least, `from pycalphad import io as database_io` is available as a workaround. I'd be on board with a comment being added to `pycalphad/io/__init__.py`, pointing to this issue, to say no object names should be elevated to discourage importing `pycalphad.io` into user code as `io`.

For pycalphad developers, we almost always use fully qualified or relative imports (I can't think of a case in the code where we don't), and implicit relative imports were removed in Python 3, so `import io` should never pick up `pycalphad.io`, even from inside the pycalphad package directory.

**Comment by bocklund** [comment]
I agree. I don't think a comment is necessary.
