### ISSUE TITLE
Parameters with active components that are not in the Phase constituent array produce incorrect models

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#256]
The `Phase` object's constituent array (corresponding to the `CONSTITUENT` TDB keyword) defines the only species allowed to be active in each sublattice.

If a parameter is defined with an active species in a sublattice and that species is not in the Phases's constituent array it will produce a `Model` that is inconsistent with the Phase constituent array, which produces either convergence failures at best and silent garbage data or segmentation faults at worst. This is because the parameter searches by Model do not filter out parameters that have active species in sublattices they do not belong in.

Below are two failing tests that should pass when this is fixed. In this case, `B` is an active component in the ALPHA phase, but according to ALPHA's constituent array, B can only be present in the second sublattice, not the first. In the database below, there's a parameter that defines B in the first sublattice, which it cannot exist in.

A fix for this issue would be for Models to be created that do not include parameters that are not consistent with constituent array. A warning should also be emitted, since the either the parameter or constituent array may be unintentionally inconsistent and the user should be alerted to fix the problem.

```python
from pycalphad import Database, Model, equilibrium, variables as v
import numpy as np

TDB_BAD_CONSTITUENTS = """
ELEMENT A BLANK 0 0 0 !
ELEMENT B BLANK 0 0 0 !

TYPE_DEFINITION % SEQ * !
DEFINE_SYSTEM_DEFAULT ELEMENT 2 !

PHASE ALPHA %  2 0.5 0.5 !
CONSTITUENT ALPHA :A: A,B :  !

$  ALPHA  $
PARAMETER G(ALPHA,A:A;0) 1 -10; 10000 N !
PARAMETER G(ALPHA,A:B;0) 1 -10; 10000 N !

$ Erroneous parameter! B is not in the first sublattice
PARAMETER G(ALPHA,B:A;0) 1 1e5; 10000 N !
"""

def test_bad_constituents_not_in_model():
    dbf = Database(TDB_BAD_CONSTITUENTS)
    mod = Model(dbf, ['A', 'B'], 'ALPHA')
    assert v.SiteFraction('ALPHA', 0, 'B') not in mod.ast.free_symbols


def test_bad_constituents_do_not_affect_equilibrium():
    dbf = Database(TDB_BAD_CONSTITUENTS)
    assert np.isclose(equilibrium(dbf, ['A', 'B'], ['ALPHA'], {v.P: 101325, v.T: 300, v.N: 1, v.X('B'): 0.5}).GM.values.squeeze(), -10.0)
```

**Comment by igorjrd** [comment]
Hi Brandon,

I noticed that the inconsistent parameters are being instantiated when method `Model.redlich_kister_sum()` is called. I tried to simply skip instantiation of parameters that do not have constituents to satisfy one sublattice of its model.
```
            consts_in_subl=[True for n in range(len(param['constituent_array'])) 
                if (param['constituent_array'][n][0] in self.constituents[n])]
            if sum(consts_in_subl) < len(self.constituents):
                ConditionWarning('Database specifies parameters for incompatible sublattice configurations')
                continue
```
This approach seems to solve the problem and did not caused failures in almost all pycalphad tests. Unfortunately, two tests of `test_equilibrium` presented failures with this bugfix approach. A curious fact is that either failed tests are related to issue #43 (`test_eq_issue43_chempots_misc_gap` and `test_eq_issue43_chempots_tricky_potentials`).
I checked manually if there were any differences between the `reference_energy` and `free_symbols` of issue #43 case. Either were equal to the results obtained without my bugfix proposal, for both phases of the case.

**Comment by bocklund** [comment]
Yes, this is a possible solution.  Another could be to change the `param_query` to add/modify a test on the constituent array, e.g. the following lines are used in the `reference_energy` to search for endmembers that make up the surface of reference for a phase:

```python
        pure_param_query = (
            (where('phase_name') == self.phase_name) & \
            (where('parameter_order') == 0) & \
            (where('parameter_type') == "G") & \
            (where('constituent_array').test(self._purity_test))  # <--- here
        )
```

For example, the `_purity_test` used here (code copied below) is actually what causes the bad parameters to get selected from the Database and used in the `redlich_kister_sum` in the first place.

```python
    def _purity_test(self, constituent_array):
        """
        Check if constituent array only has one species in its array
        This species must also be an active species
        """
        if len(constituent_array) != len(self.constituents):
            return False
        for sublattice in constituent_array:
            if len(sublattice) != 1:
                return False
            if (sublattice[0] not in self.components) and \
                (sublattice[0] != v.Species('*')):
                return False
        return True
```

You can see from this code that the code only checks that the species in that sublattice are in the *active components*, but what should really be tested is that they are active species in the sublattice (i.e. the corresponding sublattice of `self.constituents`).

**Comment by igorjrd** [comment]
I see. I improved `_purity_test` to check if each `constituent_array` sublattice is in the correspondent model sublattice described in `self.components`, as in the following code:

```python
    def _purity_test(self, constituent_array):
        """
        Check if constituent array only has one species in its array
        This species must also be an active species
        """
        if len(constituent_array) != len(self.constituents):
            return False
        for param_sublattice, model_sublattice in zip(constituent_array, self.constituents):
            if len(param_sublattice) != 1:
                return False
            if (param_sublattice[0] not in self.components) and \
                param_sublattice[0] not in model_sublattice and \
                (param_sublattice[0] != v.Species('*')):
                return False
            if param_sublattice[0] not in model_sublattice:
                return False
        return True
```
What about this approach? All the tests worked well using this.

**Comment by bocklund** [comment]
The `Model._array_validity` and `Model._interaction_test` are also used to check constituent arrays, do you think those will be affected by this issue also?

**Comment by bocklund** [comment]
Also, if I may make a suggestion on your code, it might be better to reorganize the checks

```python
    def _purity_test(self, constituent_array):
        """
        Check if constituent array only has one species in its array
        This species must also be an active species
        """
        if len(constituent_array) != len(self.constituents):
            return False
        for param_sublattice, model_sublattice in zip(constituent_array, self.constituents):
            if len(param_sublattice) != 1:
                return False
            if param_sublattice[0] not in model_sublattice and \
                (param_sublattice[0] != v.Species('*')):
                return False
        return True
```

1. The check for whether the species (`param_sublattice[0]`) is in the components is redundant when also checking if the species is in the `model_sublattice`, because only the active species are in `self.constituents` ([see here](https://github.com/pycalphad/pycalphad/blob/d711006754ac6f7ad660cf512f64763884b0a05c/pycalphad/model.py#L141)):

```
sublattice_comps = set(sublattice).intersection(self.components)
... <snip>
self.constituents.append(sublattice_comps)
```

2. The last statement `if param_sublattice[0] not in model_sublattice:` is also redundant given the previous statement.

**Comment by igorjrd** [comment]
`Model._array_validity` and `Model._interaction_test` are quite similar, differing only by checking condition `len(sublattice) > 1` in `._interaction_test`.
`Model._purity_check` also have its similarities with `_array_validity`, being the condition check `len(sublattice) != 1` the main difference between these methods until this issue. I think that would be appropriate to call `_array_validity` during `_interaction_test` and `_purity_check` executions, keeping the differences to `_array_validity` in the referred methods.
Sorry about the last `if param_sublattice[0] not in model_sublattice:`. It was an unconscious addition.

**Comment by bocklund** [comment]
I think that would be a good solution. Can you write up a PR with those changes and the test from this issue. It would also be nice if you could add a couple unit tests for the changes you make to `_interaction_test` and `_array_validity` as well, to validate the expected behavior and the behavior of this bug.
