### ISSUE TITLE
[Feature Request] Enable broadcasting over parameters

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#265]
It would be great for ESPEI, uncertainty quantification or parametric studies to be able to  to broadcast calls to `calculate` or `equilibrium` over sets of parameters.

**Comment by richardotis** [comment]
This has been possible to do for a while (since introduction of `IndependentPotential` at least).

```python
from pycalphad import equilibrium, Database, variables as v
v.V0001 = v.IndependentPotential('V0001')
eq = equilibrium(Database('alzn_mey.tdb'), ['AL', 'ZN', 'VA'], ['FCC_A1', 'HCP_A3', 'LIQUID'],
                conditions={v.N: 1, v.P: 1e5, v.T: (300, 1000, 1), v.X('ZN'): 0.3, v.V0001: (-100, 100, 10)})
```

Note that the corresponding parameter (`V0001` here) should be undefined in the database file, i.e., no FUNCTION with that name defined, or else it won't work.
