### ISSUE TITLE
ipopt 3.13.1 correctness at equilibrium compositions near zero.

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#271]
It seems that for some spurious cases, the solver fails to find the correct solution when compositions are close to the edge of composition space.

In the particular case below, the chemical potentials for Li appear wrong for Li compositions near zero in for the `LIQUID` phase with constituent array of `LI, LI4SN, SN`. I was not able to reproduce this issue in the `BCC` phase, which has a constituent array of `LI, SN`.

I was able to verify a change in behavior between ipopt versions:

Old: 

```
# Name                    Version                   Build  Channel
cyipopt                   0.1.9           py37h3b54f70_1000    conda-forge
ipopt                     3.12.12           h2b3c609_1006    conda-forge
```

New: 

```
cyipopt                   0.1.9           py38h65ad66c_1003    conda-forge
ipopt                     3.13.1               hbb27dc6_0    conda-forge
```

I used the following script to calculate chemical potentials and save them to files:

```python
# coding: utf-8
from pycalphad import Database, calculate, equilibrium, variables as v, Model, ReferenceState
import numpy as np

XS = np.logspace(-12, -8, 101)
dbf = Database('Li-Sn.tdb')
comps = ['LI', 'SN', 'VA']
phases = ['LIQUID']
eq = equilibrium(dbf, comps, phases, {v.P: 101325, v.N: 1, v.T: 300, v.X('LI'): XS})
Li_mu = eq.MU.values.squeeze()[:, 0]
# if old ipopt:
np.savetxt('old.ipopt.txt', Li_mu)
# If new ipopt:
# np.savetxt('new.ipopt.txt', Li_mu)
```

Then to plot the following figure:

```python
import numpy as np
import matplotlib.pyplot as plt

XS = np.logspace(-12, -8, 101)

new = np.loadtxt('new.ipopt.txt')
old = np.loadtxt('old.ipopt.txt')

plt.semilogx(XS, old, label='old ipopt')
plt.semilogx(XS, new, label='new ipopt')
plt.legend()
plt.xlabel('X(LI)')
plt.ylabel('MU(LI)')
plt.savefig('ipopt-compare.png', bbox_inches='tight')
```

![ipopt-compare](https://user-images.githubusercontent.com/7681751/79021419-72f96f00-7b49-11ea-85fa-4d88ec6e9933.png)

The TDB file is attached below, with a `.txt` extension so GitHub would let me upload it.

[Li-Sn.tdb.txt](https://github.com/pycalphad/pycalphad/files/4463347/Li-Sn.tdb.txt)

**Comment by richardotis** [comment]
I can reproduce this locally.

**Comment by richardotis** [comment]
As of `db5086c` I get more physically reasonable but still incorrect results.
![download](https://user-images.githubusercontent.com/6405510/119228783-793a7880-bac9-11eb-809f-fb13401a9c0e.png)
This isn't surprising since the convergence criteria in the new solver are not tuned to handle the dilute case effectively. The disagreement starts right at about the current mass residual tolerance.

**Comment by richardotis** [comment]
A few important notes:
1. `pycalphad.core.equilibrium._adjust_conditions` forces all composition conditions to a minimum of `MIN_SITE_FRACTION*1000`, which in the current implementation is `8e-10`, so we wouldn't expect chemical potentials below that composition to be correct anyway.
2. It appears that `MIN_SITE_FRACTION = 8e-13` may be too big for this system (remember one of the challenges for this system is the large formula unit for some of the species in the liquid).

We can address both issues simultaneously by setting `MIN_SITE_FRACTION = 1e-16` and then adjusting the mass residual tolerance from `1e-8` to `min(1e-8, np.min(spec.prescribed_elemental_amounts)/10)`. When we do that, we get much better agreement.
![download (87)](https://user-images.githubusercontent.com/6405510/119233541-8ada4b00-bade-11eb-921d-89c27c07906d.png)

**Comment by richardotis** [comment]
Note that I get several failures in the test suite with those changes, so it needs more work to generalize to other systems.

**Comment by bocklund** [comment]
> pycalphad.core.equilibrium._adjust_conditions forces all composition conditions to a minimum of MIN_SITE_FRACTION*1000, which in the current implementation is 8e-10, so we wouldn't expect chemical potentials below that composition to be correct anyway.

This is almost exactly the point where the solution starts to deviate in the figure you shared.

**Comment by richardotis** [comment]
Note the fix for this issue included setting the minimum allowed composition to `1e-10`, so while the convergence issues for the chemical potential are solved, calculations below `X(A)=1e-10` are not possible without modifying the solver. (I tried setting the minimum value to `1e-12`, but convergence was inconsistent for other dilute systems.) We may revisit this in the future with an improved set of convergence criteria.
