### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by fospald** [pycalphad/pycalphad#275]
I installed the [latest Anaconda version](https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh) and then pycalphad as described in the docs on a Ubuntu 18.04.4 LTS. 
I tried to run the first example from the tutorial:

```
import matplotlib.pyplot as plt
from pycalphad import Database, binplot
import pycalphad.variables as v

# Load database and choose the phases that will be considered
db_alzn = Database('alzn_mey.tdb')
my_phases_alzn = ['LIQUID', 'FCC_A1', 'HCP_A3']

# Create a matplotlib Figure object and get the active Axes
fig = plt.figure(figsize=(9,6))
axes = fig.gca()

# Compute the phase diagram and plot it on the existing axes using the `plot_kwargs={'ax': axes}` keyword argument
binplot(db_alzn, ['AL', 'ZN', 'VA'] , my_phases_alzn, {v.X('ZN'):(0,1,0.02), v.T: (300, 1000, 10), v.P:101325, v.N: 1}, plot_kwargs={'ax': axes})

plt.show()
```

and got the following error:

> binplot(db_alzn, ['AL', 'ZN', 'VA'] , my_phases_alzn, {v.X('ZN'):(0,1,0.02), v.T: (300, 1000, 10), v.P:101325, v.N: 1}, plot_kwargs={'ax': axes})
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/plot/binary.py", line 48, in binplot
>     full_eq = equilibrium(dbf, comps, phases, conds, **eq_kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/core/equilibrium.py", line 341, in equilibrium
>     properties = dask.compute(properties, scheduler=scheduler)[0]
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/base.py", line 437, in compute
>     results = schedule(dsk, keys, **kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 527, in get_sync
>     return get_async(apply_sync, 1, dsk, keys, **kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 494, in get_async
>     fire_task()
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 466, in fire_task
>     callback=queue.put,
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 516, in apply_sync
>     res = func(*args, **kwds)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 227, in execute_task
>     result = pack_exception(e, dumps)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
>     result = _execute_task(task, data)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
>     return func(*args2)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/utils.py", line 29, in apply
>     return func(*args, **kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/core/calculate.py", line 373, in calculate
>     final_ds['points'].values = np.arange(len(final_ds['points']))
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/xarray/core/common.py", line 262, in __setattr__
>     object.__setattr__(self, name, value)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/xarray/core/dataarray.py", line 562, in values
>     self.variable.values = value
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/xarray/core/variable.py", line 2115, in values
>     f"Cannot assign to the .values attribute of dimension coordinate a.k.a IndexVariable {self.name!r}. "
> ValueError: Cannot assign to the .values attribute of dimension coordinate a.k.a IndexVariable 'points'. Please use DataArray.assign_coords, Dataset.assign_coords or Dataset.assign as appropriate.

I tried to fix the error by installing an older version of xarray 
conda install xarray=0.14.1
now I get the error

> Traceback (most recent call last):
>   File "al-zn-example.py", line 14, in <module>
>     binplot(db_alzn, ['AL', 'ZN', 'VA'] , my_phases_alzn, {v.X('ZN'):(0,1,0.02), v.T: (300, 1000, 10), v.P:101325, v.N: 1}, plot_kwargs={'ax': axes})
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/plot/binary.py", line 48, in binplot
>     full_eq = equilibrium(dbf, comps, phases, conds, **eq_kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/core/equilibrium.py", line 341, in equilibrium
>     properties = dask.compute(properties, scheduler=scheduler)[0]
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/base.py", line 437, in compute
>     results = schedule(dsk, keys, **kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 527, in get_sync
>     return get_async(apply_sync, 1, dsk, keys, **kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 494, in get_async
>     fire_task()
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 466, in fire_task
>     callback=queue.put,
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 516, in apply_sync
>     res = func(*args, **kwds)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 227, in execute_task
>     result = pack_exception(e, dumps)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
>     result = _execute_task(task, data)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
>     return func(*args2)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/core/lower_convex_hull.py", line 97, in lower_convex_hull
>     comp_idx = np.ravel_multi_index(it.multi_index[len(indep_conds):], comp_coord_shape)
>   File "<__array_function__ internals>", line 6, in ravel_multi_index
> ValueError: parameter multi_index must be a sequence of length 1
> Traceback (most recent call last):
>   File "al-zn-example.py", line 14, in <module>
>     binplot(db_alzn, ['AL', 'ZN', 'VA'] , my_phases_alzn, {v.X('ZN'):(0,1,0.02), v.T: (300, 1000, 10), v.P:101325, v.N: 1}, plot_kwargs={'ax': axes})
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/plot/binary.py", line 48, in binplot
>     full_eq = equilibrium(dbf, comps, phases, conds, **eq_kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/core/equilibrium.py", line 341, in equilibrium
>     properties = dask.compute(properties, scheduler=scheduler)[0]
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/base.py", line 437, in compute
>     results = schedule(dsk, keys, **kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 527, in get_sync
>     return get_async(apply_sync, 1, dsk, keys, **kwargs)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 494, in get_async
>     fire_task()
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 466, in fire_task
>     callback=queue.put,
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 516, in apply_sync
>     res = func(*args, **kwds)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 227, in execute_task
>     result = pack_exception(e, dumps)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
>     result = _execute_task(task, data)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
>     return func(*args2)
>   File "/home/felix/anaconda3/lib/python3.7/site-packages/pycalphad/core/lower_convex_hull.py", line 97, in lower_convex_hull
>     comp_idx = np.ravel_multi_index(it.multi_index[len(indep_conds):], comp_coord_shape)
>   File "<__array_function__ internals>", line 6, in ravel_multi_index
> ValueError: parameter multi_index must be a sequence of length 1

What am I doing wrong? I guess something in xarray and numpy is incompatible in the most recent version to pycalphad?

**Comment by bocklund** [comment]
Hey @fospald, this looks pretty similar to an issue on our [Google group](https://groups.google.com/forum/#!topic/pycalphad/mOgvkJbUGtg). The problem was an out of date pycalphad and I suspect you are seeing a similar issue, since the dask code in your traceback here has been removed since `pycalphad=0.8.1`  Could you check what version you are on? The latest release is `pycalphad=0.8.3`.

**Comment by fospald** [comment]
That is true, conda installed pycalphad-0.7.1.post2.
I deleted everything and downloaded [miniconda](https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh) and explicity run the installation with
`conda install -c pycalphad -c conda-forge pycalphad=0.8.3`
Now it is working! Thank you!
