### ISSUE TITLE
The service seems to be down when using pycalphad in jupyer notebook

### ISSUE THREAD

**Issue by xiongziyi1900** [pycalphad/pycalphad#277]
I have installed the pycalphad module in my Anaconda base environment and the conda list includes the packages such as cyipopt c++-complier needed for computation. However, when I use the jupyter notebook to run the code from examples, I always meet the problem which says "The service seems to be down, but it will restart immediately". And I check the terminal which says "KernelRestarter: restarting kernel (1/5), keep random ports kernel cc41b54c-51e3-425c-b903-699286d5be39 restarted". I have tried to uninsall Anaconda but it doesn't work. I also tried to use the python 3.8 which I installed before in the computer and the pip command to install the pycalphad, but this can't continue without ipopt which is diffcult to get.  So I have to try to propose this issue here. I would be appreciate if you can help me solve this problem !

**Comment by richardotis** [comment]
Some users have recently reported problems with installing pycalphad into the Anaconda base environment. (Our next release should fix this.) Can you try installing pycalphad into a new conda environment? I would also try using Python 3.7 for the environment. The command is `conda create -c pycalphad -conda-forge -n calphad python=3.7 pycalphad==0.8.3 jupyter notebook` and after it's complete you would run `conda activate calphad` and then `jupyter notebook`

**Comment by richardotis** [comment]
After walking through this issue with another user, this seems to be solved by using `python-symengine==0.6.1`, which pycalphad currently won't let you do because of the version pin `python-symengine==0.6`. We need to bump the version pin in a new release to fix this issue.

**Comment by richardotis** [comment]
A temporary workaround is:
```
conda remove --force python-symengine
pip install symengine==0.6.1
```
This should probably be done in a fresh environment, since this workaround will make it harder to upgrade the environment in the future.

**Comment by xiongziyi1900** [comment]
Thanks very much for your advice!!! It works successfully. I did it in a new conda environment which may not influence the base environment. Looking forward to the next release and more functions of pycalphad!

**Comment by bocklund** [comment]
I'm closing this issue because it seems to be solved. Thanks, @richardotis!
