### ISSUE TITLE
installing pycalphad via anaconda results in a version conflict python 3.8 not supported see photo

### ISSUE THREAD

**Issue by Pcascone** [pycalphad/pycalphad#283]
the photo is a screen shot of the anaconda prompt results
![anaconda installation of pycalphad](https://user-images.githubusercontent.com/73666893/97623529-052c6c00-19e3-11eb-8a29-d29a373840a0.PNG)
I have tried to install as per the instructions but there appears to be a version conflict with python 3.8

**Comment by bocklund** [comment]
We just released pycalphad 0.8.4 yesterday and a Windows build through the conda pycalphad channel is coming in the next day or two. Can I add a comment in this issue when the Windows build is released and have you try again?

**Comment by Pcascone** [comment]
That would be most appreciated Brandon Thank you
Will the new build support python 3.8 or 3.9?

**Comment by Pcascone** [comment]
Richard
The new update still resulted in multiple conflicts reported by anaconda. The screen filled with file conflicts and I terminated the anaconda prompt after one hour and it was still working through files.

Sent from iPhone
Paul Cascone

Cell 1-858-736-7393


On Oct 30, 2020, at 10:35 AM, Richard Otis <notifications@github.com> wrote:

﻿

We just released pycalphad 0.8.4, and the Windows versions went live today. These versions include support for Python 3.8. Please give this another try and let us know how it goes.

**Comment by richardotis** [comment]
Try creating a separate conda environment for the installation.

The command is: `conda create -n calphad -c pycalphad -c conda-forge pycalphad==0.8.4 jupyterlab`

Then you would type `conda activate calphad` to switch to the environment, and then `jupyter lab` to start Jupyter.

**Comment by Pcascone** [comment]
Thanks Richard also does it matter if I am using the 64 or 32 bit anaconda?
I have the 64 bit installed.

Sent from iPhone
Paul Cascone

Cell 1-858-736-7393


On Oct 30, 2020, at 1:11 PM, Richard Otis <notifications@github.com> wrote:

﻿

Try creating a separate conda environment for the installation.

The command is: conda create -n calphad -c pycalphad -c conda-forge pycalphad==0.8.4 jupyterlab

Then you would type conda activate calphad to switch to the environment, and then jupyter lab to start Jupyter.

**Comment by Pcascone** [comment]
Richard
That didn’t work. Conda reported that 0.8.4 was not found but it is obviously there at anaconda.org
I think there is an issue with anaconda.
Very frustrated that 119,000 downloaded the package and I can’t get it to work!

Paul Cascone

Cell 1-858-736-7393


On Oct 30, 2020, at 1:11 PM, Richard Otis <notifications@github.com> wrote:

﻿

Try creating a separate conda environment for the installation.

The command is: conda create -n calphad -c pycalphad -c conda-forge pycalphad==0.8.4 jupyterlab

Then you would type conda activate calphad to switch to the environment, and then jupyter lab to start Jupyter.

**Comment by Pcascone** [comment]
Richard
I updated conda, created a new environment and pycalphad loaded with the usual command.


Sent from iPhone
Paul Cascone

Cell 1-858-736-7393


On Oct 30, 2020, at 1:11 PM, Richard Otis <notifications@github.com> wrote:

﻿

Try creating a separate conda environment for the installation.

The command is: conda create -n calphad -c pycalphad -c conda-forge pycalphad==0.8.4 jupyterlab

Then you would type conda activate calphad to switch to the environment, and then jupyter lab to start Jupyter.

**Comment by richardotis** [comment]
Great, Paul. I was just looking at this again and confirmed that creating a fresh environment works on Windows.
