### ISSUE TITLE
SymEngine RuntimeError: Not implemented

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#304]
Hello all,

I'm new using pycalphad. I'm trying to calculate the HM_MIX of my phase for different disordered fraction sets of a A2-B2 ternary phase. The CEF is given:
A2: (A,B,VA)1(A,B,VA)6
B2: (A,B,VA)0.5(A,B,VA)0.5(C,VA)6
I could calculate the HM of the phase but when I set: output='HM_MIX' I have this error:

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-53-ca5b8ff06e86> in <module>
----> 1 result_HM = calculate(dbf_feti, comps, 'BCC_B2',P=101325, T=1400, output='HM_MIX', pdens=1000)

~/opt/pycalphad/pycalphad/core/calculate.py in calculate(dbf, comps, phases, mode, output, fake_points, broadcast, parameters, to_xarray, **kwargs)
    375                                    models=models, parameters=parameters,
    376                                    output=output, callables=callables, build_gradients=False, build_hessians=False,
--> 377                                    verbose=kwargs.pop('verbose', False))
    378     str_statevar_dict = collections.OrderedDict((str(key), unpack_condition(value)) \
    379                                                 for (key, value) in statevar_dict.items())

~/opt/pycalphad/pycalphad/codegen/callables.py in build_phase_records(dbf, comps, phases, conds, models, output, callables, parameters, verbose, build_gradients, build_hessians)
    202                                     additional_statevars=state_variables,
    203                                     build_gradients=build_gradients,
--> 204                                     build_hessians=build_hessians)
    205 
    206     # If a vector of parameters is specified, only pass the first row to the PhaseRecord

~/opt/pycalphad/pycalphad/codegen/callables.py in build_callables(dbf, comps, phases, models, parameter_symbols, output, build_gradients, build_hessians, additional_statevars)
    113         out = out.xreplace(dict(zip(undefs, undef_vals)))
    114         build_output = build_functions(out, tuple(state_variables + site_fracs), parameters=parameter_symbols,
--> 115                                        include_grad=build_gradients, include_hess=build_hessians)
    116         cf, gf, hf = build_output.func, build_output.grad, build_output.hess
    117         _callables['callables'][name] = cf

~/opt/pycalphad/pycalphad/core/cache.py in wrapper(*args, **kwds)
    139                         stats[HITS] += 1
    140                         return result
--> 141                 result = user_function(*args, **kwds)
    142                 with lock:
    143                     root, = nonlocal_root

~/opt/pycalphad/pycalphad/codegen/sympydiff_utils.py in build_functions(sympy_graph, variables, parameters, wrt, include_obj, include_grad, include_hess, func_options, grad_options, hess_options)
    112     inp = sympify(variables + parameters)
    113     graph = sympify(sympy_graph).xreplace({zoo: oo})
--> 114     func = lambdify(inp, [graph], **_get_lambidfy_options(func_options))
    115     if include_grad or include_hess:
    116         grad_graphs = list(graph.diff(w).xreplace({zoo: oo}) for w in wrt)

~/opt/miniconda3/lib/python3.7/site-packages/symengine/__init__.py in lambdify(args, exprs, **kwargs)
     33 
     34     def lambdify(args, exprs, **kwargs):
---> 35         return Lambdify(args, *exprs, **kwargs)
     36 
     37 

symengine_wrapper.pyx in symengine.lib.symengine_wrapper.Lambdify()

symengine_wrapper.pyx in symengine.lib.symengine_wrapper._Lambdify.__init__()

symengine_wrapper.pyx in symengine.lib.symengine_wrapper.LLVMDouble._init()

RuntimeError: Not implemented.
```

Am I missing something?

Thank you
EA

_Originally posted by @Ebert-Daniel in https://github.com/pycalphad/pycalphad/issues/268#issuecomment-781338801_

**Comment by bocklund** [comment]
@ebert-daniel, I moved your comment on #268 to a new issue so we can keep the discussion of this issue separate from the pull request.

This error means that some part of the expression for `HM_MIX` of one of your phases can't be handled by SymEngine's `lambdify`. There are some known issues with workarounds, but it's hard to say what the issue is without access to the expression. Are you able to share the TDB file (privately is okay if you are not able to share publicly)?

Also: `HM_MIX` _might_ not be what you want. `_MIX` properties are referenced to the endmembers of the same phase, rather than the pure elements of the same phase. There's some documentation and examples of these different behaviors here: https://pycalphad.org/docs/latest/examples/ReferenceStateExamples.html. [This example](https://pycalphad.org/docs/latest/examples/ReferenceStateExamples.html#special-mix-reference-state) demonstrates what `HM_MIX` reference means for a phase with multiple sublattices. If you want to know the mixing energy with respect to the pure elements, then you want to use pycalphad's `ReferenceState` objects and use `Model.shift_reference_state`.

**Comment by bocklund** [comment]
This is expected behavior since https://github.com/pycalphad/pycalphad/pull/205. `_MIX` properties are special properties that have the reference state set to the endmembers. The endmembers are ambiguous for order-disorder models, since they have contributions from both the ordered endmebmers and disordered endmembers. Interested readers should see the discussion in #205 for more details.

To calculate the (more traditional) thermodynamic mixing energy, `Model.shift_reference_state` should be used to set the reference state of the pure elements to the energy of this phase (B2 in this case), then the `HMR` propery can be used. There's an example in the docs that shows how to do this and gives some more details on the differences between `HM_MIX` and `HMR`.

This issue could be closed, but it might make sense to think about a way to better report this issue.

**Comment by bocklund** [comment]
I wrote some code that generates a warning instead of giving this error silently. It reads:

```
pycalphad/pycalphad/model.py:362: UserWarning: B2_BCC is a partitioned model with an ordering energy contribution. The choice of endmembers for the endmember reference model used by `_MIX` properties is ambiguous for partitioned models. The `Model.set_reference_state` method is a better choice for computing mixing energy. See https://pycalphad.org/docs/latest/examples/ReferenceStateExamples.html for an example.
```

I'm wondering if it would be better to raise an exception? The only compelling reason I can think of to _not_ raise an exception is that `_MIX` properties will still work correctly and not trigger this error for `equilibrium` calcluations where the partitioned phase is not stable. OTOH, an argument _for_ raising an exception is that not raising one can lead to surprising results where `equilibrium` calculations work for some conditions, but not others (depending on whether or not the partitioned phase is stable).

@richardotis what do you think?

**Comment by richardotis** [comment]
Warn for now, we can always make it raise later. As long as we keep the number of warnings propagated to the user low, we'll avoid warning fatigue.
