### ISSUE TITLE
Bug in order-disorder models when species other than VA are present in the "vacancy sublattice"

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#310]
Below I have a complete, runnable example that demonstrates an error in handling order-disorder phases with non-vacancy constituents in the vacancy sublattice.

Given a binary A-B subsystem of a hypothetical A-B-C system, we can define a couple different sublattice models for the ordered phase (named `ORDERED`):

1. `(A,B,VA)(A,B,VA)(VA)` (suffixed in the test with `_VA_VA`, since there are vacancies in the disordered sublattice and "vacancy" sublattice)
2. `(A,B,VA)(A,B,VA)(C,VA)`(suffixed in the test with `_VA_VA_C `, since there are vacancies in the disordered sublattice and vacancies and C in the "vacancy" sublattice)
3. `(A,B)(A,B)(VA)` (suffixed in the test with `_VA_C `, since there are vacancies and C in the "vacancy" sublattice)

Now we can define a binary A-B model (`Model(db_{suffix}, ["A", "B", "VA"], "ORDERED")`) for each system and check the energy of pure A. 

The test shows that `_VA_VA` and `_VA_C` produce the correct energy for pure A (-10 kJ in this case), but the `_VA_VA_C` produces an incorrect energy (0 kJ in this case). 

There are two issues at play here:

1. Even though component `C` is not active in the model, the answer changes. This is because [this line](https://github.com/pycalphad/pycalphad/blob/be404461ad44a4677897a0cc0d843dd7bec1007e/pycalphad/model.py#L982) is identifying the vacancy sublattice by the Phase object's (active and inactive) constituents, rather than the Model object's active constituents. It might be necessary to look at the phase model so that we don't mis-identify a sublattice as a vacancy sublattice, but I think we could use a better heuristic to determine the vacancy sublattice and eliminate this as a potential bug.
2. [This `if` statement](https://github.com/pycalphad/pycalphad/blob/be404461ad44a4677897a0cc0d843dd7bec1007e/pycalphad/model.py#L985) incorrectly classifies the last sublattice as "not a vacancy sublattice"  in `_VA_C` and `_VA_VA_C` cases, since the vacancy sublattice of the Phase constituents contains more than one species. That leads to the `Model.mole_fractions` of species in this sublattice to be substituted for site fractions, which is incorrect. The incorrect behavior only manifests if `VA` is present in other sublattices than the vacancy sublattice (i.e. the `_VA_VA_C` case). The `_VA_C` gives the correct answer because for the wrong reason because `Model.mole_fractions` for `VA` in the vacancy sublattice reduces to `1`.  

The behavior is really subtle and only occurs if the vacancy sublattice has multiple constituents (active and inactive constituents, since we use `Phase.constituents`) AND one or more of those constituents shows up in the other sublattices.

```python
from pycalphad import Database, Model, variables as v
from pycalphad.tests.test_energy import check_energy

def test_order_disorder_interstitial_sublattice():
    TDB_OrderDisorder_VA_VA = """
    ELEMENT VA   VACUUM   0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT A    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT B    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT C    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !

    DEFINE_SYSTEM_DEFAULT ELEMENT 2 !
    DEFAULT_COMMAND DEF_SYS_ELEMENT VA !

    TYPE_DEFINITION % SEQ *!
    TYPE_DEFINITION & GES A_P_D DISORD MAGNETIC  -1.0    4.00000E-01 !
    TYPE_DEFINITION ( GES A_P_D ORDERED MAGNETIC  -1.0    4.00000E-01 !
    TYPE_DEFINITION ' GES A_P_D ORDERED DIS_PART DISORD ,,,!

    PHASE DISORD  %&  2 1   3 !
    PHASE ORDERED %('  3 0.5  0.5  3  !

    CONSTITUENT DISORD  : A,B,VA : VA :  !
    CONSTITUENT ORDERED  : A,B,VA : A,B,VA : VA :  !

    PARAMETER G(DISORD,A:VA;0)  298.15  -10000; 6000 N !
    PARAMETER G(DISORD,B:VA;0)  298.15  -10000; 6000 N !

    """

    TDB_OrderDisorder_VA_VA_C = """
    $ Compared to TDB_OrderDisorder_VA_VA, this database only
    $ differs in the fact that the VA sublattice contains C

    ELEMENT VA   VACUUM   0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT A    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT B    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT C    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !

    DEFINE_SYSTEM_DEFAULT ELEMENT 2 !
    DEFAULT_COMMAND DEF_SYS_ELEMENT VA !

    TYPE_DEFINITION % SEQ *!
    TYPE_DEFINITION & GES A_P_D DISORD MAGNETIC  -1.0    4.00000E-01 !
    TYPE_DEFINITION ( GES A_P_D ORDERED MAGNETIC  -1.0    4.00000E-01 !
    TYPE_DEFINITION ' GES A_P_D ORDERED DIS_PART DISORD ,,,!

    PHASE DISORD  %&  2 1   3 !
    PHASE ORDERED %('  3 0.5  0.5  3  !

    CONSTITUENT DISORD  : A,B,VA : C,VA :  !
    CONSTITUENT ORDERED  : A,B,VA : A,B,VA : C,VA :  !

    PARAMETER G(DISORD,A:VA;0)  298.15  -10000; 6000 N !
    PARAMETER G(DISORD,B:VA;0)  298.15  -10000; 6000 N !

    """

    TDB_OrderDisorder_VA_C = """
    $ Compared to TDB_OrderDisorder_VA_VA_C, this database only
    $ differs in the fact that the disorderd sublattices do not contain VA

    ELEMENT VA   VACUUM   0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT A    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT B    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !
    ELEMENT C    DISORD     0.0000E+00  0.0000E+00  0.0000E+00 !

    DEFINE_SYSTEM_DEFAULT ELEMENT 2 !
    DEFAULT_COMMAND DEF_SYS_ELEMENT VA !

    TYPE_DEFINITION % SEQ *!
    TYPE_DEFINITION & GES A_P_D DISORD MAGNETIC  -1.0    4.00000E-01 !
    TYPE_DEFINITION ( GES A_P_D ORDERED MAGNETIC  -1.0    4.00000E-01 !
    TYPE_DEFINITION ' GES A_P_D ORDERED DIS_PART DISORD ,,,!

    PHASE DISORD  %&  2 1   3 !
    PHASE ORDERED %('  3 0.5  0.5  3  !

    CONSTITUENT DISORD  : A,B : C,VA :  !
    CONSTITUENT ORDERED  : A,B : A,B : C,VA :  !

    PARAMETER G(DISORD,A:VA;0)  298.15  -10000; 6000 N !
    PARAMETER G(DISORD,B:VA;0)  298.15  -10000; 6000 N !

    """

    db_VA_VA = Database(TDB_OrderDisorder_VA_VA)
    db_VA_C = Database(TDB_OrderDisorder_VA_C)
    db_VA_VA_C = Database(TDB_OrderDisorder_VA_VA_C)

    mod_VA_VA = Model(db_VA_VA, ["A", "B", "VA"], "ORDERED")
    mod_VA_C = Model(db_VA_C, ["A", "B", "VA"], "ORDERED")
    mod_VA_VA_C = Model(db_VA_VA_C, ["A", "B", "VA"], "ORDERED")

    # Site fractions for pure A
    subs_dict = {
        v.Y('ORDERED', 0, v.Species('A')): 1.0,
        v.Y('ORDERED', 0, v.Species('B')): 0.0,
        v.Y('ORDERED', 0, v.Species('VA')): 0.0,
        v.Y('ORDERED', 1, v.Species('A')): 1.0,
        v.Y('ORDERED', 1, v.Species('B')): 0.0,
        v.Y('ORDERED', 1, v.Species('VA')): 0.0,
        v.Y('ORDERED', 2, v.Species('VA')): 1.0,
        v.T: 300.0,
    }

    check_energy(mod_VA_VA, subs_dict, -10000, mode='sympy')
    check_energy(mod_VA_C, subs_dict, -10000, mode='sympy')
    check_energy(mod_VA_VA_C, subs_dict, -10000, mode='sympy')


test_order_disorder_interstitial_sublattice()
```

Thanks to @Ebert-Daniel for pointing this out to me via email.

**Comment by Ebert-Daniel** [comment]
Thank you @bocklund for providing a runnable sample of that issue. I'm willing to contribute in any sense

**Comment by bocklund** [comment]
@Ebert-Daniel can you try to test the database you're working on against the branch in #311? #311 introduces some simple automated tests, but it would be great if you could validate your more complex database against another software.

Let me know if you need any help getting a development environment set up. We have some instructions for [installing a development environment](https://pycalphad.org/docs/latest/INSTALLING.html#installing) and you can also install the additional dependencies for running tests with pytest and building the sphinx documentation based on our [environment-dev.yaml](https://github.com/pycalphad/pycalphad/blob/develop/environment-dev.yml) conda requirements file (the last five packages are the additional ones beyond the core dependencies: `pytest`, `pytest-cov`, `ipython`, `sphinx`, `sphinx_rtd_theme`).
