### ISSUE TITLE
DOC: pycalphad installation documentation overhaul

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#320]
The installation docs could be improved:

## General issues

1. Conda environments (also in above). Consider what to do for release versions. Environments are best practices and it's a lot easier to manage pycalphad starting from a clean slate environment with no packages installed. Many of our users are relatively new Python and/or Conda users and forgetting to activate is such a common gotcha that we've advocated to install into `base`. If we do choose to install into an environment, it's critical for users to install Jupyter into the environment too (and make sure that Jupyter from the `base` environment can pick up the kernel - it might be necessary to install `nb_conda`, but I'm not sure.)
2. Most pycalphad users probably also want to install Jupyter, though it is not an explicit dependency for the package. It's in `base` today (but maybe won't be forever?) and needs to be installed separately for other environments.

## Development mode specific issues

3. (Windows) Windows users need to bring their own compilers. Installing the `c-compiler` and `cxx-compiler` packages on Windows basically gives the [`vc` package](https://github.com/conda-forge/vc-feedstock), which provides an [activation script](https://github.com/conda-forge/vc-feedstock/blob/master/recipe/activate.bat) for a user-installed MSVC.
4. (Windows) Most Windows users will also need to install `git`, since it does not come with the OS.

Windows Subsystem for Linux is an option, but it's not a "true" Windows installation and users advanced enough to install and use WSL should be able to follow the instructions as a Linux user (and recognize that they should do so). [This tutorial](https://beenje.github.io/blog/posts/how-to-setup-a-windows-vm-to-build-conda-packages/) is linked to in the conda-forge documentation and really good and simple for walking users through installing `git` and a compatible MSVC compiler. Users can be instructed to skip to the "Developer tools installation" section.

5. Users should be instructed to create Conda environments for development versions. Activating has an extra barrier, but ideally most users interested in development installations should be familiar enough to use Conda environments and it's worth the extra protection from wrecking the `base` environment or losing a release version of pycalphad
6. The development mode steps should include steps to build a working pycalphad without installing and removing it.

**Comment by bocklund** [comment]
Update: with the new minimizer (#329), shipping wheels is possible and we are going to move towards officially supporting pip for installing pycalphad.

1. Still not sure about environments vs. not. For non-conda installs environments with `venv` can be trickier for beginners to manage because they may not realize that it installs to a certain place. The nice thing about conda environments is they can be activated globally. Maybe another package/environment manager is better at this on the non-conda side now, but I am not ready to endorse anything yet.
2. Since pip is going to be the way forward with optional conda, it won't necessarily come for free and makes it clear that for both pip and conda installs, we can include explicitly installing Jupyter in the instructions, but say it is optional

_

6. pip will make this much easier now.
7. Should we include conda development mode instructions at all? For releases, I think we should.

**Comment by richardotis** [comment]
Perhaps GitHub Codespaces or Gitpod could be a solution to the issues with setting up a Windows development environment. For Codespaces, you can even link a local VSCode to the remote containerized environment.
