### ISSUE TITLE
equilibrium: Detecting single-phase regions

### ISSUE THREAD

**Issue by broshe** [pycalphad/pycalphad#33]
Hi Richard,
I get a strange result from a seemingly simple calculation:

from pycalphad import Database, equilibrium
import pycalphad.variables as v

db = Database('/home/ebrosh/Documents/ebroshWorks/tcworks/Al-Fe-solidification/alfe_sei.TDB')

data = equilibrium(db, ['AL', 'FE','VA'], ['LIQUID','AL13FE4'], {v.X('FE'): 1.0e-1, v.T: 1500, v.P: 1e5},verbose=False)

print('phases')
print(data['Phase'].values.flatten())
print('  ')
print('phase fractions')
print(data['NP'].values.flatten())
print('  ')
print('composition of the two phases')
print(data['X'].sel(component='FE').values.flatten())

The output is:
phases
['LIQUID' 'LIQUID']
  
phase fractions
[ 0.58441188  0.41558812]
  
composition of the two phases
[ 0.09999928  0.10000101]

Why two liquid phases instead of one?
There should not be a miscibility gap there.

Best regards,
Eli

**Comment by richardotis** [comment]
Right now pycalphad can't tell the difference between a single-phase region and a really small miscibility gap. Notice that the two compositions on the tie line are really close together, near the numerical limit of the solver. In this case the phase fractions returned don't mean anything.

For now, pycalphad will always return a tie region with the maximum number of phases allowed by the Gibbs phase rule, and you tell the single phase regions apart by checking how far apart the compositions / site fractions are.

Eventually pycalphad will automatically convert really small tie lines of the same phase into single phase regions automatically.

**Comment by richardotis** [comment]
Fixed in 31022d3b1eba9a04026cbe9643cdf53b3c69e7ba
