### ISSUE TITLE
Database parsing fails if some tokens are not uppercase

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#359]
Here's a failing test that reproduces the issue that could be added to `test_database.py`:

```python
from pycalphad import Database
from pycalphad.tests.datasets import ALFE_TDB

def test_load_lowercase():
    "Test loading a database coerced to lowercase loads correctly."
    dbf = Database.from_string(ALFE_TDB, fmt='tdb')
    dbf_lower = Database.from_string(ALFE_TDB.lower(), fmt='tdb')
    assert dbf == dbf_lower
```

**Comment by ingenious452** [comment]
Hey I am new to opensource and would like to contribute, could you explain what the issue is and what I have to do.

**Comment by richardotis** [comment]
@ingenious452 To start, you can install the development version of pycalphad by following the instructions here: https://pycalphad.org/docs/latest/INSTALLING.html#development-version
Then you should try to run the above test code by putting the following into a separate Python script:
```python
from pycalphad import Database
from pycalphad.tests.datasets import ALFE_TDB

def test_load_lowercase():
    "Test loading a database coerced to lowercase loads correctly."
    dbf = Database.from_string(ALFE_TDB, fmt='tdb')
    dbf_lower = Database.from_string(ALFE_TDB.lower(), fmt='tdb')
    assert dbf == dbf_lower
    
test_load_lowercase()
```
When you run this script (`python mytestscript.py`), you should get an `AssertionError` as the output of the script. That's how you know you're reproducing the bug! Once you get to this step, we can talk about ways to fix the bug.

**Comment by richardotis** [comment]
@ingenious452 Someone else fixed this issue already, but feel free to take a look at pycalphad's list of other open beginner bugs: https://github.com/pycalphad/pycalphad/labels/beginner
