### ISSUE TITLE
Ternary figure size

### ISSUE THREAD

**Issue by tkphd** [pycalphad/pycalphad#371]
The default figure size in matplotlib.pyplot is small, and for offline rendering it's nice to be able to specify a figure size. I've hacked my local clone to pass `**kwargs` in to `plt.subplots` instead of `plt.scatter` in `eqplots.py`, but there's probably a better, more systematic way of passing some options to each instead of choosing one or the other for everyone. This decision seems better made by a team member.

Example of my hacky interface:

```python
...
pltargs = {"figsize": (10, 9)}
ternplot(tdb, species, phases, conditions, x=XA, y=XC, **pltargs)
plt.savefig(figfile, dpi=400, bbox_inches="tight")
...
```

**Comment by bocklund** [comment]
The `ternplot` API documentation could be improved. It's a wrapper around `eqplot`, which has a [keyword argument for the axes](https://pycalphad.org/docs/latest/api/pycalphad.plot.html#pycalphad.plot.eqplot.eqplot), `ax`, which `eqplot` will then use to plot on.

I usually work in this pattern:

```python
import matplotlib.pyplot as plt
from pycalphad import Database, ternplot
from pycalphad import variables as v

dbf = Database('/Users/brandon/tdbs/Cr-Fe-Ni.tdb')
comps = ['CR', 'FE', 'NI', 'VA']
phases = list(dbf.phases.keys())
conds = {v.T: 830, v.P:101325, v.X('CR'): (0,1,0.02), v.X('NI'): (0,1,0.02)}

fig = plt.figure(figsize=(10, 9))
ax = fig.add_subplot(projection='triangular')
ternplot(dbf, comps, phases, conds, x=v.X('CR'), y=v.X('NI'), ax=ax)
fig.savefig('tern-fig.png', dpi=400)
```

**Comment by bocklund** [comment]
Closing this as resolved.
