### ISSUE TITLE
problem with calculating equilibirum

### ISSUE THREAD

**Issue by zhongjingjogy** [pycalphad/pycalphad#39]
Hi Otis,

Recently, I tried to do some calculation which relies on the computation of equilibrium for the Al-Ni system with FCC_A1 and gamma prime phase. I tried to do this with the pycalphad, but it turned out that there are some difference among different implementations of the computation of equilibrium.

By setting temperature as 873.15K, pressure as 101325, and the molar fraction of Al as 0.2, I got results from Thermo-Calc, opencalphad and pycalphad.

Result from opencalphad(the result from Thermo-Calc is the same as opencalphad.)
<pre><code>
Some data for components ...................................:
Component name    Moles      Mole-fr  Chem.pot/RT  Activities  Ref.state
AL                2.0000E-01  0.20000 -2.4583E+01  2.1080E-11  SER (default)   
NI                8.0000E-01  0.80000 -5.2649E+00  5.1701E-03  SER (default)   

Some data for phases .......................................:
Name                Status Moles      Volume    Form.Units  At/FU dGm/RT  Comp:
FCC_A1.................. E  2.626E-01  0.00E+00  2.63E-01    1.00  0.00E+00  X:
 NI     8.94297E-01  AL     1.05703E-01
 Constitution: Sublattice  1 with     2 constituents and     1.000000 sites
 NI     8.94297E-01  AL     1.05703E-01
               Sublattice  2 with     1 constituents and     1.000000 sites
 VA     1.00000E+00

GAMMA_PRIME............. E  7.374E-01  0.00E+00  7.37E-01    1.00  0.00E+00  X:
 NI     7.66422E-01  AL     2.33578E-01
 Constitution: Sublattice  1 with     2 constituents and     0.750000 sites
 NI     9.99841E-01  AL     1.58647E-04
               Sublattice  2 with     2 constituents and     0.250000 sites
 AL     9.33838E-01  NI     6.61624E-02
</code></pre>
Result from pycalphad
<pre><code>
X = [ 0.2272507,  0.7727493], [ 0.1060816,  0.8939184]
Y = [  3.64443392e-04,   9.99635557e-01,   9.07909485e-01, 9.20905148e-02],
          [ 1.06081603e-01,   8.93918397e-01,   1.00000000e+00, nan]
</code></pre>

At present, I would like to use opencalphad because it produces the same result as the Thermo-Calc, though the result from pycalphad is closed to the opencalphad. I wonder whether this is problem for pycalphad. I report this and hope this might be helpful.

By the way, the APIs designed in pycalphad is very convenient. And here is how I called pycalphad to obtain the result above
<pre><code>
db = Database('alnicrre.tdb')
my_phases = ['FCC_A1', 'GAMMA_PRIME']
eq = equilibrium(db, ['AL', 'NI', 'VA'], my_phases, {v.X('AL'): 0.2, v.T: 873.15, v.P: 101325})
print eq.get("X")
print eq.get("Y")
</code></pre>

Best wishes,

Jing

**Comment by richardotis** [comment]
Hi Jing,

Thank you for your message. You should definitely trust the result from Thermo-Calc and OpenCalphad. pycalphad's energy minimization routine currently has trouble with tiny site fractions, so sometimes it cannot achieve good convergence when they are smaller than 1e-2 or so. Sometimes it works, sometimes it doesn't. I have attempted some solutions for this but they make the calculation very slow.

Unfortunately I do not have time to fix this yet, but I am hoping to solve the problem by the end of the summer.

**Comment by richardotis** [comment]
If you want you can also try manually adjusting the point density for the calculation, like

```python
# default 'pdens' is 100
equilibrium(db, ['AL', 'NI', 'VA'], my_phases, {v.X('AL'): 0.2, v.T: 873.15, v.P: 101325}, calc_opts={'pdens': 200})
```

**Comment by zhongjingjogy** [comment]
I raise the point density to 1000 and it finally reach a result the same as the opencalphad and pycalphad. 

Here are the result,
X = array([[[[[ 0.23357854,  0.76642146],
          [ 0.10570285,  0.89429715]]]]])
Y = array([[[[[  1.58639953e-04,   9.99841360e-01,   9.33838246e-01,
             6.61617537e-02],
          [  1.05702851e-01,   8.94297149e-01,   1.00000000e+00,
                        nan]]]]])

I used to compute the equilibrium by calling the opencalphad using subprocess. It seems that when proper point density is chosen I have no need to do this any more. I would like to try something else.

Thanks!
