### ISSUE TITLE
write_tdb function no longer works

### ISSUE THREAD

**Issue by wahab2604** [pycalphad/pycalphad#399]
I have been using the write_tdb function to write out my database objects, since updating to pycalphad 0.10 and therefore symengine 0.90, I now get this error:
![image](https://user-images.githubusercontent.com/55495976/159342677-635b4e3d-34cd-4879-9ce9-72397b868d21.png)

If I downgrade to the previous version of pycalphad and symengine it works

Thanks

**Comment by richardotis** [comment]
Can you share the TDB file you're getting this error with? If there's no TDB file, you could also pickle the Database object to share it with
```python
import pickle
pickle.dump(dbf, open("output.pkl","wb"))
```
Then you could share the pkl for us to investigate.

**Comment by wahab2604** [comment]
I upgraded back to the latest version and got this pickle file
[output.zip](https://github.com/pycalphad/pycalphad/files/8318530/output.zip)

**Comment by richardotis** [comment]
Hm, I'm getting an error when I try to unpickle it. Would you be comfortable modifying the source code of your pycalphad installation? If you go to `/opt/conda/lib/python3.9/site-packages/pycalphad/io.tdb.py` and go to line 468, just before that line add a `print(expr)`. Then when you re-run we ought to see the expression that's causing the failure.

**Comment by richardotis** [comment]
That particular piece of code should only be triggered when you try to write out an expression with a non-integer exponent, like `(2+T)**(4.78)` or `(2+T)**(x)`. Other packages that read TDBs will normally not support that anyway, which is why it'll raise an error. Would it be possible to put together a minimal example that reproduces the problem?

**Comment by wahab2604** [comment]
I'll try and produce a minimal example, but I double checked the functions and I don't have any non-integer exponents. I have negative integer exponents and Log and Exp terms because 3rd generation calphad functions I use.

**Comment by wahab2604** [comment]
I think I found the issue, I had seperated the EXP terms to make the 3rd gen compatible with Thermocalc.
e.g 
AC2S0 =  1 - EXP(-336.7341251748639*T**(-1))
AC2S = -0.007007095043242937*T**2 +91.78273041807118*T*LN(AC2S0#)

For AC2S0, expr.args[1] is -336.76../T and it cannot do the int check in the tdb.py (line 468). 

I can remove the function that separates these terms and it works, but I had it in to make these functions compatible with Thermocalc (it always had issues with a LN and EXP term in the same line)

**Comment by richardotis** [comment]
Strange. I can't reproduce the issue locally:
```python
from symengine import S
from pycalphad.io.tdb import TCPrinter
expr = S('1 - EXP(-336.7341251748639T**(-1))')
TCPrinter()._stringify_expr(expr)
```
```
'1-1*EXP(-336.7341251748639/T)'
```

**Comment by richardotis** [comment]
Ah, this will do it:
```python
expr = S('exp(-336.7341251748639T**(-1))')
TCPrinter()._stringify_expr(expr)
```
```
RuntimeError: Symbol cannot be evaluated.
```

**Comment by richardotis** [comment]
The fix will basically look like
```python
# line 467
        elif isinstance(expr, Pow):
            if expr.args[0] == E:
                # This is the exponential function
                return 'exp(' + self._stringify_expr(expr.args[1]) + ')'
```
