### ISSUE TITLE
Ternary isothermal phase diagram plotting

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#4]
Ternary isothermal diagrams have a lot of performance and accuracy problems, especially when dealing with phases with internal degrees of freedom but small solubility. See the below example for Cr-Ti-V.

![image](https://cloud.githubusercontent.com/assets/6405510/5600928/8fc03a20-92b4-11e4-91dc-30b846faab90.png)

Correct diagram (from NIMS phase diagram database):
![image](https://cloud.githubusercontent.com/assets/6405510/5600930/a82d0ad4-92b4-11e4-9570-f66a784c43b4.png)

The complete solution isn't clear, but it probably starts with a binplot-style rewrite and heavy CPU/memory profiling. Verification of the test databases using commercial software should also be done prior to any further work.

**Comment by richardotis** [comment]
This hasn't been "fixed" but the old way of computing this diagram has been removed. The new equilibrium engine can in principle do this calculation, and it's something I'd like to reintroduce and get working well during the 0.3.x cycle for 0.4.

**Comment by bocklund** [comment]
I tried to reproduce this using the [NIMS database](http://cpddb.nims.go.jp/cpddb/Multicomponent/crtiv/crtiv.htm) and was getting the error with this call to equilibrium:

`equilibrium(dbf, ['CR', 'TI', 'V', 'VA'], dbf.phases.keys(), {v.T: 873, v.P: 101325, v.X('CR'): (0,1, 0.1), v.X('TI'): (0,1,0.1), })` 

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-70-5621bdbd01a2> in <module>()
----> 1 result = equilibrium(dbf, comps, phases, {v.T: 873, v.P: 101325, v.X('CR'): (0,0.8, 0.1), v.X('TI'): (0,1,0.1), })#v.X('TI'): (0, 1, 0.1)})

/Users/brandon/Projects/pycalphad/pycalphad/core/equilibrium.py in equilibrium(dbf, comps, phases, conditions, output, model, verbose, broadcast, calc_opts, scheduler, parameters, compute_constraints, **kwargs)
    340                                                          [np.atleast_1d(sl)[ch] for ch, sl in zip(chunk, slices)])))]
    341             job = delayed(_solve_eq_at_conditions, pure=False)(dbf, comps, prop_slice, phase_records,
--> 342                                                               list(str_conds.keys()), verbose, diagnostic, compute_constraints)
    343             res.append(job)
    344         properties = delayed(_merge_property_slices, pure=False)(properties, chunk_grid, slices, list(str_conds.keys()), res)

/Users/brandon/Projects/pycalphad/pycalphad/core/eqsolver.pyx in pycalphad.core.eqsolver._solve_eq_at_conditions (pycalphad/core/eqsolver.c:12282)()

UnboundLocalError: local variable 'phases' referenced before assignment
```
I can do the binaries, but not the ternary. Am I missing something?

**Comment by richardotis** [comment]
It looks like it's an issue with [the handling for sum of compositions greater than 1](https://github.com/pycalphad/pycalphad/blob/08f978ea171823532c570fd9bb6da081774e81be/pycalphad/core/eqsolver.pyx#L411). I think it's old code that got shuffled around and managed not to get caught in testing. It isn't necessary to use `len(phases)` there; I think just using `:` should work.

**Comment by bocklund** [comment]
I'll try to fix and submit a PR later this week. Then I'll try to reproduce this and see where we are at regarding this issue.

**Comment by bocklund** [comment]
For now, I'll just patch around it. I think we'll handle this more elegantly when we add support for advanced conditions.

**Comment by bocklund** [comment]
The plotting part of this issue is covered in #5 and #98.

There are still a fair amount of convergence failures on the triangular branch (develop branch core: 0f8f0e387b28f658259e7529e1c5a8ccafdf548c)  in the Cr-Ti-V database I used with the current pdens default of 500, but the solubility is much more correct. Overall this is much improved from an accuracy standpoint in the solubility region and the calculation was done in 5 minutes with the CompiledModel and 1 at. % step sizes in compositions.

![Cr-Ti-V](https://user-images.githubusercontent.com/7681751/26895078-38cb9706-4b75-11e7-99bf-013b79588056.png)


There low alpha-Cr2Ti region is not so bad, but we do seem to have regressed a little in other places. Should we close this or come up some specific action items? Or maybe we could wait until after the fix memory branch is merged.

**Comment by bocklund** [comment]
Thermo-Calc actually has some trouble with the BCC miscibility gap also

![tc-ti-cr-v](https://user-images.githubusercontent.com/7681751/26896267-fbaff020-4b78-11e7-9b9f-d3e8459d1281.png)

**Comment by bocklund** [comment]
Now that I realized that #5 is for iso*pleth* not iso*therm*, are there specific accuracy action items that we can set or will #98 close this?

**Comment by richardotis** [comment]
I expect #98 will close this issue. You can put "fixes gh-98" or similar in the commit message for the squashed commit once the PR is approved, and GH will automatically close this issue when it is merged.
