### ISSUE TITLE
bug in core/halton.py

### ISSUE THREAD

**Issue by BlazejGrabowski** [pycalphad/pycalphad#449]
calling
`pts = halton(4, 49, scramble=False)`
produces a zero in pts[48,3] which is wrong

the correct value is 0.00291545

the problem occurs in the mod_matrix calculation when calling
`np.floor(sum_matrix)`
for the problematic entry, sum_matrix is 0.9999999999999999 and floor brings it down to 0, while it should result in 1

adding an epsilon at float precision to sum_matrix does the job, but I have not checked whether it can cause a problem at another place

version: pycalphad 0.10.1

**Comment by richardotis** [comment]
Hi Blazej, thanks for your report and analysis. Your solution should work fine without significant consequences. Would you like to submit a pull request with the fix?

**Comment by BlazejGrabowski** [comment]
Hi Richard, if you don't mind, I'd leave the fix to you
Thx for pycalphad, it's a fantastic tool, in particular for teaching

**Comment by richardotis** [comment]
Sure, I'll try to get to it soon.
