### ISSUE TITLE
Calculation assigns wrong colors to phases in the legend. Sorting does not help.

### ISSUE THREAD

**Issue by vahid2364** [pycalphad/pycalphad#465]
Hi

I tried calculating the free energy curves for binary Al-Li at 400K. At first glance, the energy curves look good. The legend command, however, assigns the wrong colors to phases. Below is the code I used. The sorted command (sorted(phases)) does not resolve the problem. My database is Al-Li-Zn by Guo et al., and I removed Zn before calculating.

```

dbf = Database('Al_Li_Zn_Guo.tdb')

temp = 400

comps = list(dbf.elements)  
comps.remove('/-')
comps.remove('ZN') 
print(comps)

phases = ['AL2LI3', 'AL4LI9', 'FCC_A1', 'LIQUID','B32']

# Get the colors that map phase names to colors in the legend
legend_handles, colorlist = phase_legend((phases))

fig = plt.figure(figsize=(9,6))
ax = fig.gca()

# Loop over phases, calculate the Gibbs energy, and scatter plot GM vs. X(RE)
for phase_name in phases:
    result = calculate(dbf, comps, phase_name, P=101325, T=temp, output='GM')
    ax.scatter(result.X.sel(component='LI'), result.GM, marker='o', s=5)
    if (phase_name == 'AL2LI3'):
        plt.annotate('Gibbs Energy of AL2LI3',xy = (0.61,np.max(result.GM.values)), xytext=(0.66, np.max(result.GM.values)), arrowprops=dict(facecolor='black', shrink=0.05))
    elif (phase_name == 'AL4LI9'):
        plt.annotate('Gibbs Energy of AL4LI9',xy = (0.70,np.max(result.GM.values)), xytext=(0.74, np.max(result.GM.values)), arrowprops=dict(facecolor='black', shrink=0.05))


# Format the plotgege
ax.set_title('Free energy curves at '+str(temp)+'K' )
ax.set_xlabel('X(LI)')
ax.set_ylabel('GM')
ax.set_xlim((0, 1))
ax.legend(handles=legend_handles, loc='center left', bbox_to_anchor=(1, 0.6))

plt.show()
```

The image file that I get is:
<a href="https://ibb.co/D17jX2q"><img src="https://i.ibb.co/kGhPnCd/G-energies-at400-K.png" alt="G-energies-at400-K" border="0"></a>

**Comment by richardotis** [comment]
Try changing this line: `ax.scatter(result.X.sel(component='LI'), result.GM, marker='o', s=5)`
to `ax.scatter(result.X.sel(component='LI'), result.GM, marker='o', s=5, c=colorlist[phase_name])`

**Comment by vahid2364** [comment]
Thanks! That solved the issue. FYI, I have included the new image here. I am developing teaching materials based on PyCalphad for the Thermodynamics undergraduate course, and two of these tutorials can be found on my GitHub page.

<a href="https://ibb.co/hFNZbx6"><img src="https://i.ibb.co/qY8WKLS/FE-image.png" alt="FE-image" border="0"></a>

**Comment by richardotis** [comment]
Thank you! I may be teaching Thermodynamics again in the fall, so I may follow up with you on this over the summer as I pull new teaching materials together.

You may also be interested in what Penn State has done:
- https://github.com/PhasesResearchLab/PSU-MatSE410
- https://github.com/PhasesResearchLab/PSU-MatSE580-2020
