### ISSUE TITLE
open MatCalc open database

### ISSUE THREAD

**Issue by yinrong** [pycalphad/pycalphad#467]
May I use open databse in pycalphad?

I download the database from
https://www.matcalc.at/index.php/databases/open-databases

and my python code reports error

![image](https://user-images.githubusercontent.com/4221569/231164913-cd41f79e-8451-49f7-8331-1c66fc69f687.png)

by `download` I mean copy the content and save again.   the original download file also reports `invalid char` error.

**Comment by richardotis** [comment]
The Matcalc open databases don't work out of the box, for a few reasons. Try the versions of the Matcalc databases available here: https://github.com/materialsgenomefoundation/2021-workshop-material/tree/main/pycalphad/databases

The `.pycalphad.tdb` means we modified them to work with pycalphad.
