### ISSUE TITLE
Scheil solidification result problem: fraction liquid is always 1

### ISSUE THREAD

**Issue by amy6chunxiao** [pycalphad/pycalphad#469]
Hi, I load the following database and do Scheil solidification, but only find the  liquid phase. 

https://github.com/materialsgenomefoundation/2021-workshop-material/blob/main/pycalphad/databases/mc_al_v2.032.pycalphad.tdb

My code is as follows:
![image](https://user-images.githubusercontent.com/10076079/232366076-216849f0-303a-42d9-932c-fbf5fd538d61.png)

The phase fraction is：
![test](https://user-images.githubusercontent.com/10076079/232366377-05f18804-7030-4ec2-b219-20392eab702a.jpg)

**Comment by richardotis** [comment]
Try adding vacancies (`VA`) to `comps`. Most of the solid solution phases in that database include an empty interstitial sublattice, and pycalphad will not load them unless vacancies are explicitly included.

**Comment by amy6chunxiao** [comment]
Hi, when I add (VA) to comps,  it raises an error:

ValueError: Number of interstitial sublattices for the disordered phase (1) and the ordered phase (5) do not match. Got substitutional sublattice indices of [].

**Comment by richardotis** [comment]
Try excluding the `GP_MAT` phase.
```python
phases = sorted(set(dbf.phases.keys()) - {'GP_MAT'})
```

**Comment by amy6chunxiao** [comment]
已收到邮件
