### ISSUE TITLE
New project domain: pycalphad.org

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#47]
https://readthedocs.org/projects/pycalphad/builds/4264743/
https://readthedocs.org/projects/pycalphad/builds/4264744/

Relevant error:
```
error: python-dateutil 1.5 is installed but python-dateutil<3.0.0,>=2.1 is required by set(['botocore'])
```

This might be a good excuse to move off of RTD for good, especially since it is still before the first pycalphad paper has been submitted (so we can change the docs URL etc.)

@bocklund Have you made any progress with Travis-CI and gh-pages integration?

**Comment by bocklund** [comment]
There are a couple ways to generate Sphinx docs and push them onto a gh-pages branch. RTD has an advantage in being able track documentation for multiple branches, which I haven't seen recreated in any gh-pages implementation I've come across. 

I think that it could be possible that two sets of docs could be maintained, but it would require a bit of clever template writing in Sphinx that I haven't looked into. My idea would be to have the master and develop branches build to two sub directories (e.g. repo/stable and repo/latest, similar to RTD)  have a link on each page that would send you to the opposing docs. So each link would replace the 'stable' or 'latest' to the opposing one. For example, the page `pycalphad.github.io/latest/api/modules.html` would contain a link to `pycalphad.github.io/stable/api/modules.html`. 

Again, I'm not sure if it's possible, but I think it is a good starting point if we want to try and publish multiple versions of the docs on gh-pages.

**Comment by richardotis** [comment]
Promising approach for deploying to gh-pages (check the comments too):
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

We could easily change the `rm` command to only delete files in a subdirectory of the current branch or tag (given by `git describe`). We'd check out the repo at the current commit, build the docs, copy the build artifact to a temporary directory, `git reset --hard`, checkout gh-pages branch, remove all the files in the corresponding docs subdirectory, then copy the build products there. After that it would look pretty much the same as the given script.

I definitely think the approach to credential management should be to create a machine GitHub account and generate a key pair for it. It's possible to configure that account to only have push access to the gh-pages branch of this repo.

**Comment by richardotis** [comment]
I've been able to get the docs to build and deploy, but there's a problem with the relative paths in the generated HTML. I haven't been able to figure out how to fix it yet.

**Comment by richardotis** [comment]
Adding a .nojekyll file to the gh-pages root seems to have fixed it. It was not deploying all the subdirectories with underscores at the beginning of the name.

**Comment by richardotis** [comment]
I've reconfigured Travis and the gh-pages (needs to be renamed now) branch to deploy to S3. I'm waiting on DNS to propagate before pushing a new release with new addresses.

**Comment by richardotis** [comment]
The `gh-pages` branch has been renamed to `website`.
