### ISSUE TITLE
Database: Issue importing tdb. file

### ISSUE THREAD

**Issue by Tibaum31** [pycalphad/pycalphad#524]
Dear pycalphad,

I am new to pycalphad and currently I am trying to import a .tdb file, to simulate a equilibrium isothermal ternary diagram of Al, Ti and Cu, and the following error occurs:

ParseException: Expected TCCommand 'ELEMENT', found ' '  (at char 1), (line:1, col:2)

I am using the aluminum database form matcalc (https://www.matcalc.at/index.php/databases/open-databases), and I am not sure how to fix the .tdb file. I greatly appreciate your help.

For the simulation/display of the ternary diagram I used the the following code: 

_%matplotlib inline
from pycalphad import Database, ternplot
from pycalphad import variables as v
tdb = Database('mc_al_v2036.tdb')
comps = ['AL', 'TI', 'CU', 'VA']
phases = list(tdb.phases.keys())
conds = {v.T: 1073, v.P:101325, v.X('AL'): (0,1,0.015), v.X('TI'): (0,1,0.015)}
%time ternplot(tdb, comps, phases, conds, x=v.X('AL'), y=v.X('TI'))_

Thank you

Here is the .tdb-file I use:

[mc_al_v2036.tdb.zip](https://github.com/pycalphad/pycalphad/files/15050691/mc_al_v2036.tdb.zip)

**Comment by richardotis** [comment]
The Matcalc open databases do not work directly in pycalphad without modification. We have pre-modified copies available in this workshop repository: https://github.com/materialsgenomefoundation/2023-workshop-material/tree/03be5e6300feffc9350ad5094b7e9485b26f1c42/pycalphad/databases

I do notice that there are new versions available on the Matcalc website. We haven't modified the new versions yet.

**Comment by Tibaum31** [comment]
Thank you very much for the fast response!
I tried the database "_mc_al_v2.032.pycalphad.tdb_" in the following code, using Jupyter notebook: 

_%matplotlib inline
from pycalphad import Database, ternplot
from pycalphad import variables as v
tdb = Database('mc_al_v2.032.pycalphad.tdb')
comps = ['AL', 'TI', 'CU', 'VA']
phases = list(tdb.phases.keys())
conds = {v.T: 1073, v.P:101325, v.X('AL'): (0,1,0.015), v.X('TI'): (0,1,0.015)}
%time ternplot(tdb, comps, phases, conds, x=v.X('AL'), y=v.X('TI'))_

,but now the following Value error occurs: 

ValueError: Number of interstitial sublattices for the disordered phase (1) and the ordered phase (5) do not match. Got substitutional sublattice indices of [].

Is this a known error or can you maybe help me with that?
Thank you!

**Comment by bocklund** [comment]
The MatCalc Al database in the workshop material has been fixed now https://github.com/materialsgenomefoundation/2023-workshop-material/tree/03be5e6300feffc9350ad5094b7e9485b26f1c42/pycalphad/databases

#541 improves the error message so it's easier to track which phases cause the issue.

The phase diagram currently produced by the `develop` branch is below:
<img width="773" alt="Screenshot 2024-07-11 at 5 19 30 PM" src="https://github.com/user-attachments/assets/5e25cbd9-83b9-45a3-8a45-4d641025b00b">

and the new mapping branch we're working on:
<img width="784" alt="Screenshot 2024-07-11 at 5 20 19 PM" src="https://github.com/user-attachments/assets/f344e5f8-ecef-4ab0-aa27-b440b9a5ae3e">

**Comment by bocklund** [comment]
As this is a database issue, I think it's sufficiently resolved to close.
