### ISSUE TITLE
Preserve line numbers in TDB parser tracebacks?

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#540]
Not sure if it's possible, (it probably is at least annoying to implement) but it would be cool if we could preserve line numbers in the original file when we hit parse exceptions, e.g. the lsat bit of of the Exception produced by pyparsing:

`pyparsing.exceptions.ParseException: Expected TCCommand 'BMAGN', found '('  (at char 13), (line:1, col:14)`

**Comment by richardotis** [comment]
We will need to associate line numbers with each line of the database file, and somehow propagate the information about lines that are removed (e.g., comments). There may also be some kind of approach involving calculating offsets of the removed lines.
