### ISSUE TITLE
Mixing properties are incorrect for phases with non-chemical energy contributions

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#55]
The reason is, e.g., `GM_MIX`, is only subtracting out the contribution from `self.models['ref']`, which only includes the chemical energy contribution to each end-member. For phases with magnetic, Einstein, or some custom end-member contributions, the result will not be correct.

Standard properties like `GM`, `CPM`, etc., appear to be fine.

**Comment by richardotis** [comment]
The correct solution to this is to implement actual reference state support.

**Comment by richardotis** [comment]
Fixing this is going to require some architectural changes which I recommend deferring to 0.5.x or 0.6.

**Comment by bocklund** [comment]
Any ideas on an approach for this?

Maybe a `Model` has a `reference_contributions` property which is a list of (string/tuple) contributions that are considered 'reference'?

Then we take the current `model.reference_energy ` and rename it to (for example) `model.surface_reference_energy` (surface of reference). Then the new `model.reference_energy` is 

```python
Add(*[contrib for key, contrib in self.models.items() if key in reference_contributions])
```

If this is a reasonable approach, I can sketch something out

**Comment by bocklund** [comment]
I think it should be a drop in replacement unless we depend on the `ref` being the surface of reference somewhere else. And it allows users to set the reference state to anything they want (at any time) as long as the reference state only includes contributions that got processed through `build_phase`. 

That is also a drawback of this approach - a user cannot write a custom reference state that is not a sum of contributions to the energy (unless they include it as a contribution so it goes through `build_phase` and then override the ast later).

**Comment by bocklund** [comment]
I implemented this idea in the model-refstate branch and the demo is here 

https://nbviewer.jupyter.org/github/bocklund/notebooks/blob/master/pycalphad/model_refstates.ipynb

**Comment by bocklund** [comment]
I don't think so? It should just subtract out any contributions from the models deemed 'reference' at each set of points. If the contribution from the specific model at a given point is 0, subtracting it shouldn't matter. 

Do you have a specific model or case in mind that I should look at?

**Comment by richardotis** [comment]
I realize what my concern is now. Magnetic and Einstein contributions can have interaction parameters. How about this idea: Every contribution function gets a `mixing_only` kwarg which defaults to `False`. If `True`, the function returns the normal contribution, minus the contribution from each endmember.

**Comment by bocklund** [comment]
I see the problem now. If we use the `mixing_only` approach, what we could do is in `build_phase` make an attribute for `Model.mix_models` that is a dict with the same keys as `Model.models` but with the surface of reference subtracted out for each contribution. We could also implement as `Model.ref_models` and do the subtraction in the properties later - I don't think I have a preference here so I'ld probably just `mix_models`, which is simpler. 

However one challenge with this is that users writing their own custom models (and we would have to) encode this logic into every contribution by hand.

Maybe an alternate solution is to use the same approach (making a `mix_models` dict in `build_phase`) but instead of implementing it in each model, we try to temporarily remove (or zero out) all interactions from the Database as we construct the `mix_models` dict so the models will only use the surface of reference contributions as they are implemented in each model individually.

**Comment by bocklund** [comment]
> Does the math work out for the magnetic model?

I think so... I mean that seems to be what's happening in the implementation above. The end member contributions of the magnetic model do not give a "straight line" surface of reference, but it's still the surface of reference in that it's the contributions from the end members, right? If the endmember model parameters give some energetic contributions for site fractions between 1 and 0, is that still "mixing"? I think it is not, right? Only contributions coming from interaction parameters is "mixing"

That being said, I'm happy to discuss what you think proper reference state support looks like. Do you think it should be a function or a class that provides a transformation that we can perform on resulting datasets? I don't think it's a good strategy to add more functionality inside `calculate` and `equilibrium` and I also agree that it needs to live outside `Model`. So IMO it should stand alone and compose with everything.

**Comment by bocklund** [comment]
Thinking about ways to implement a reference state. 

What if a `ReferenceState` is a class and you can use it through a function called `apply_reference_state`, which shifts the reference state from a calculate or equilibrium Dataset by performing the requisite calculations (which could be cached in the object)

It could look something like this (we'd implement a real class, namedtuple is just for illustration)

```python
from pycalphad import variables as v
from collections import namedtuple

ReferenceState = namedtuple('ReferenceState', ['phase_name', 'conditions'])

my_refstate_298 = ReferenceState('FCC_A1', {v.T: 298.15, v.P: 101325})
# makes the reference state whatever the temperature in the calculation is
my_refstate_floating = ReferenceState('BCC_A2', {v.T: v.T, v.P: 101325})

# do it by hand, e.g. in ESPEI
eq_res = equilibruim(dbf, ['CU', 'ZR'], phases, conds)
eq_res_ref = apply_reference_state(eq_res, {'CU': my_refstate_298, Species('ZR'): my_refstate_vT})

# do it automatically, this is probably how users would interact. It's like passing a model
eq_res_ref_direct = equilibruim(dbf, ['CU', 'ZR'], phases, conds, reference_state={'CU': my_refstate_298, Species('ZR'): my_refstate_vT})
```

We can define a SER reference dict and use it by default.

**Comment by richardotis** [comment]
In fact, you could allow multi-phase and multi-component `ReferenceState`s for essentially the same amount of effort. Each calculation (all performed under the common reference state of the `Database`) defines a point on the hyperplane, and a little linear algebra recovers the chemical potentials, or "hyperplane coefficients" for general material property reference state shifts.

**Comment by bocklund** [comment]
> There would be some internal logic to determine if that set of reference states comprised a hyperplane, but otherwise looks doable

I’m confused on what you mean and why it’s necessary. 

>  I don't understand how you could apply the reference state shift after the call to equilibrium without access to the Model

You’re right. You’d have to have a more complex signature. I think I will write a function that can be used by calculate and equilibrium, but have the signature be closer to `compute_phase_values`. It wouldn’t be user-facing like calculate and equilibrium, but hopefully useful for developers


> Each specified ReferenceState would need to be its own single-phase equilibrium calculation, I think.

If you’re restricted to pure species and a phase, can’t you use calculate?

> In fact, you could allow multi-phase and multi-component ReferenceStates for essentially the same amount of effort

In a similar vein, to above. It seems like you’re saying to be able to set your reference state to FCC_L12/B2 Al-Ni. That seems strange to have a reference state like that. I would think that you’d have to decompose the reference state into the partial quantities to ensure that the hyperplane matches the same space as the calculation.

**Comment by richardotis** [comment]
For an N-component system you need N linearly independent points to define a hyperplane. For pure components that would just be the corners of composition space, but in principle you could choose a set of interior points as well. It's less common, but I've seen it used in oxide modeling before.

**Comment by bocklund** [comment]
Hm. I think it would be better to precalculate an equilibria and set the individual component reference states "by hand" (a user could possibly script this). 

If you imagine you have a reference state where you have a variable v.T condition (equivalent to `*` in Thermo-Calc), then you can have the number of phases in the reference state change with varying temperature. Couldn't that lead to over/under-specifying the reference state hyperplane?

I'm curious how that works in commercial software.

**Comment by bocklund** [comment]
Maybe it wouldn't matter.

**Comment by richardotis** [comment]
So I think we're talking about two different types of reference states. You can use a reference equilibrium calculation to define a point on the reference hyperplane directly, or you can take chemical potentials from the equilibrium calculation. Those would not give the same reference state, in general, and you're correct that the latter would complicate the reference state.

**Comment by bocklund** [comment]
It seems like there are two types of reference states that we would want to consider:

1. A phase with internal degrees of freedom specified. This includes the special case of pure component or species in a phase.
2. A set of candidate phases and conditions for an equilibrium calculation. This includes the special cases of multicomponent, mutliphase systems and systems where a component should decompose into the most stable species (e.g. O1, O2, or O3 for O in the gas phase).

I can see the path forward on the technical side, but I'm still chewing user-facing side. I want users to only see the ReferenceState class. I'll try to sketch out an implementation that can be iterated on.

**Comment by richardotis** [comment]
At the risk of over-engineering the solution, you might consider hooking ReferenceState into the dask-based framework for deferred computation that already exists in `equilibrium`. ReferenceState could contain information on how to perform the reference state calculation (including a fast-path for the Type 1 reference states you mention), but not actually compute anything until plugged in to an `equilibrium` object.
