### ISSUE TITLE
Invalid TDB syntax error when parsing COST507 database

### ISSUE THREAD

**Issue by burdickjp** [pycalphad/pycalphad#566]
I get the following error when trying to bring in the COST507 database. I've checked to see if there are different versions hosted by any of the involved parties, and they seem to be the same. 

`ParseException: Invalid TDB syntax.
 ELEMENT  Y    HCP_A3              8.89059+01  5.9664E+03  4.4434E+01 
                                          ^, found '+'  (at char 2013), (line:138, col:42)`

It looks like this is a common enough issue that a modified version exists: https://gist.github.com/bocklund/c4714ddbc0500c78e6fe255a763e7550#file-cost507-modified-tdb

**Comment by bocklund** [comment]
It's unfortunate that the typo in the mass of Y (`8.89059+01` is missing the `E` to be `8.89059E+01`) is present in a useful and widely distributed database, but I don't think we are planning to change the code to support parsing this line "correctly".

In testing against a large number of databases I've collected over the years, this particular failure mode is very uncommon. I'm actually not aware of any other database having this particular error, in a way that would make sense for us to special case it.

**Comment by bocklund** [comment]
Closing as wont-fix.
