### ISSUE TITLE
Enthalpy and Workspace

### ISSUE THREAD

**Issue by dyhliu** [pycalphad/pycalphad#579]
I calculated the enthalpy of Fe-0.1wt%C in the peritectic reaction region (1450°C-1550°C) using PyCalphad Workspace function and the mc_fe database, there were errors in the enthalpy output (eg., a decrease in HM at 1491°C).  Using Pandat and mc_fe produced accurate results.  Will PyCalphad Equilibrium function produce accurate results?  How to get('HM') from the Equilibrium results?  Thank you in advance.

Daniel

**Comment by richardotis** [comment]
If you can share the complete PyCalphad code and specific database you are using for the calculation, it will be easier to reproduce and examine your result.

**Comment by dyhliu** [comment]
Thank you, Dr. Otis.  Those errors were NaN outputs.  I think they might be failures in finding an equilibrium in PyCalphad.  I wrote codes to handle NaN output.  It worked well.  Thank you.

I replied to your response in Gmail last month.  I figured that it went nowhere.
