### ISSUE TITLE
Distribute *.c files so Cython is not required to install

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#58]
Installing `pycalphad` currently requires the user to install `Cython` on their own before installing via `setup.py`. Including the generated files will circumvent this. (It also allows `asv` benchmarks to be run)

See [http://docs.cython.org/en/latest/src/reference/compilation.html#distributing-cython-modules](http://docs.cython.org/en/latest/src/reference/compilation.html#distributing-cython-modules)

**Comment by richardotis** [comment]
This might be helpful: https://github.com/numpy/numpy/pull/4589

**Comment by bocklund** [comment]
I think I have a fix for installing with or without `Cython`, but I don't have a solution yet for automatically generating the `*.c` files when building for release. I think the `*.c` files only work with the Python version they are generated with because I was not successful when installing `pycalphad` using my compiled files that were generated in Python 3.5 in a Python 2.7 environment, so being able to release different versions with different builds is a must. 

I am curious though, since `pycalphad` requires `numpy`anyways, should requiring `Cython` be an issue? In its current state, installing `pycalphad` without `Cython` requires `numpy` and the `*.c` files and installing with `Cython` requires `Cython`, `numpy`, and `scipy` (`scipy` because of the `cimport scipy.linalg.cython_lapack as cython_lapack`)

If you want to look at my current solution, see bocklund/pycalphad@fa3f487f38c2a2df19af5f7d40756c8ebbb10776

**Comment by richardotis** [comment]
The real solution is https://www.python.org/dev/peps/pep-0518/ but there's no timeline on the implementation there. Conda-based installs of pycalphad, which are currently recommended in our documentation, are unaffected by this issue since the dependencies are resolved by conda before setup.py is called. There's a pretty good argument, IMO, for try/except on all three of those modules and re-raising the ImportErrors with slightly clearer messages that tell the user what they need to install. Anything else complicates our build process, and the further we take develop builds from release builds, the less likely we are to catch bugs before release (since all our CI is installing pycalphad in develop mode, essentially).

**Comment by bocklund** [comment]
It seems like `setup_requires` might actually be a solution, unless I am interpreting its limitations incorrectly. I agree that we should not over complicate it and have the distributions too derived from the source. I also agree that we should raise ImportErrors with better messages if `setup_requires` is not going to work.

**Comment by richardotis** [comment]
My understanding of `setup_requires` is that it is triggered after setup() has already been called, so e.g., cythonize() and numpy.get_include()  will already be called before that.

**Comment by bocklund** [comment]
I just realized that also. For the time being, it might be useful to provide a `requirements.txt` that includes Cython, numpy and scipy, so that it is easier for an end-user with pip.

**Comment by richardotis** [comment]
I like that idea, but if a user is installing pycalphad from pip, they aren't going to have easy access to any files in the release artifact.

**Comment by bocklund** [comment]
Since this won't change soon, I think there are 2 solutions:

1. Include a requirements.txt including numpy, scipy, and cython and (and other reqs) and point people to `pip install -r requirements.txt` (for installing from source)

2. In addition or instead of 1.: have a nice error message in setup.py if those packages cannot be imported. 

Either way, it's one more thing to maintain and doing nothing might be a fine alternative. Right now users either have to install from conda, read the README installation instructions (which should have this info, but does not), or know enough about what they are doing to debug the pip error messages.

**Comment by richardotis** [comment]
I like solution 2.
```
try:
    import Cython
except ImportError:
    raise ImportError("Cython must be installed before pycalphad can be installed.")
```

**Comment by bocklund** [comment]
I'll add numpy and scipy to that as well and submit a PR
