### ISSUE TITLE
Problem in hyperplane.pyx when installing pycalphad via setup.py

### ISSUE THREAD

**Issue by tjrocha7** [pycalphad/pycalphad#59]
Not sure if this is a newbie thing, a problem in my Cython module or in pycalphad: when installing pycalphad via setup.py, I get problems compiling the hyperplane.pyx file:

```Compiling pycalphad/core/hyperplane.pyx because it changed.
[1/1] Cythonizing pycalphad/core/hyperplane.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        trial_simplices[i, :] = best_guess_simplex
    cdef double[::1,:,:] trial_matrix = np.empty((num_components, num_components, num_components), order='F')
    cdef double[::1,:] candidate_tieline = np.empty((num_components, num_components), order='F')
    cdef double[::1] candidate_energies = np.empty(num_components)
    cdef double[::1] candidate_potentials = np.empty(num_components)
    cdef bint[::1] bounding_indices = np.ones(num_components, dtype=np.int32)
             ^
------------------------------------------------------------

pycalphad/core/hyperplane.pyx:90:14: Invalid base type for memoryview slice: bint

Error compiling Cython file:
------------------------------------------------------------
...
        bounding_indices[...] = True
        # Should be exactly one candidate simplex
        candidate_simplex = trial_simplices[saved_trial, :]
        for i in range(candidate_simplex.shape[0]):
            idx = candidate_simplex[i]
            candidate_tieline[i, :] = compositions[idx]
                                                 ^
------------------------------------------------------------

pycalphad/core/hyperplane.pyx:127:50: Memoryview 'double[::1]' not conformable to memoryview 'double[:]'.
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    ext_modules=cythonize(['pycalphad/core/hyperplane.pyx', 'pycalphad/core/eqsolver.pyx']),
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pycalphad/core/hyperplane.pyx```

Can someone help me on this?

**Comment by bocklund** [comment]
I'm not sure I can help with this specifically, but I noticed you are using anaconda. Have you tried installing from conda-forge?

**Comment by tjrocha7** [comment]
I have indeed, using the instructions stated in [http://pycalphad.org/docs/latest/INSTALLING.html](url) with no results:
```Fetching package metadata: ......Error: Could not find anaconda.org user conda-forg```

**Comment by bocklund** [comment]
> `Fetching package metadata: ......Error: Could not find anaconda.org user conda-forg`

Is the missing `e` in `conda-forge` a typo in your copy paste here or did you accidentally add the `conda-forg` channel instead?

**Comment by richardotis** [comment]
Are you using the latest version of Cython?

**Comment by tjrocha7** [comment]
The code line above was the output of the following inputs (it wasn't a typo):
```
conda config --add channels conda-forge
conda install pycalphad
```

These inputs are what is stated in the installation instructions. Was I doing it wrong?

In any case, do you think that the outputs I had from the setup.py installation (first comment) are a result of a bug? Because I've just updated Cython.

Thank you guys for your fast replies and sorry for being a newbie on this!

**Comment by richardotis** [comment]
I just upgraded my Cython from 0.24.1 to 0.25.1 (latest)  and am unable to reproduce your issue on Python 3.5 and Linux. What OS and version of Python are you using?

**Comment by bocklund** [comment]
Can you post the output of `conda config --show`?

**Comment by tjrocha7** [comment]
Ok so apparently I'm using Cython version 0.23.4 and I'm not able to upgrade it due to the following issue with cPickle:

```
antonio_rocha@Antonio-PC:~$ pip install cython
Traceback (most recent call last):
  File "/home/antonio_rocha/anaconda3/bin/pip", line 4, in <module>
    import pip
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/download.py", line 45, in <module>
    from pip._vendor.cachecontrol import CacheControlAdapter
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/_vendor/cachecontrol/__init__.py", line 9, in <module>
    from .wrapper import CacheControl
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/_vendor/cachecontrol/wrapper.py", line 1, in <module>
    from .adapter import CacheControlAdapter
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/_vendor/cachecontrol/adapter.py", line 5, in <module>
    from .controller import CacheController
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/_vendor/cachecontrol/controller.py", line 13, in <module>
    from .serialize import Serializer
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/_vendor/cachecontrol/serialize.py", line 8, in <module>
    from .compat import HTTPResponse, pickle, text_type
  File "/home/antonio_rocha/anaconda3/lib/python3.5/site-packages/pip/_vendor/cachecontrol/compat.py", line 8, in <module>
    import cPickle as pickle
  File "/home/antonio_rocha/anaconda3/lib/python3.5/cPickle.py", line 11
    print "a c pickle class to store and load objects to files like persistence (not persistence but ...)"
                                                                                                         ^
SyntaxError: invalid syntax
```

**Comment by tjrocha7** [comment]
Replying to @bocklund : 
```
antonio_rocha@Antonio-PC:~$ conda config --show
usage: conda config [-h] [--json] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required
```

**Comment by bocklund** [comment]
Sorry, the Mac/Linux version of Anaconda is a little different. 

Does `conda config --get channels` give you output? 

Also, that error looks like they used Python 2 print, but you're using Python 3.

**Comment by tjrocha7** [comment]
@bocklund exactly, I've been getting that error for a long time in many times I use `pip install`. I have both Python 2 and Python 3 but my `pip` is referring to Python 3 but gets `cPickle` from Python 2 and I don't understand why. And for what you said:
```
antonio_rocha@Antonio-PC:~$ conda config --get channels
--add channels 'defaults'
--add channels 'conda-forg'
--add channels 'conda-forge'
```

**Comment by bocklund** [comment]
Yeah that `conda-forge` is correct, but I think having the `conda-forg` is messing you up. Try to remove it with `conda config --remove channels conda-forg`

**Comment by tjrocha7** [comment]
Got:
```
antonio_rocha@Antonio-PC:~$ conda config --remove channels conda-forg
Error: --remove without --force is not implemented yet
```
Then I did:
```
antonio_rocha@Antonio-PC:~$ conda config --force --remove channels conda-forg
antonio_rocha@Antonio-PC:~$ conda config --get channels
--add channels 'defaults'
--add channels 'conda-forge'
```

**Comment by bocklund** [comment]
Great. Does `conda install pycalphad` work in your environment now?

**Comment by tjrocha7** [comment]
It's working! Thank you a lot! It seems to have downgraded some packages I had (like pandas), is it a problem?

Is there anywhere like a forum where I can ask/answer questions related to the module? I'm going to start working on a new project with pycalphad next week and something like that would be great.

**Comment by richardotis** [comment]
@tjrocha7 Asking questions here on the issue tracker is okay. If you have something you don't want public you can use the email address in my profile or on the personal website of @bocklund

**Comment by bocklund** [comment]
As far as downgrading packages, that should be fine for pycalphad. If you need the different versions for other projects, you should look into using [anaconda environments](http://conda.pydata.org/docs/using/envs.html], which let you manage different versions of Python and packages easily.

**Comment by tjrocha7** [comment]
Cool! Thank you guys a lot for helping!
Best regards from Portugal
