### ISSUE TITLE
Metastability with pycalphad

### ISSUE THREAD

**Issue by tjrocha7** [pycalphad/pycalphad#64]
Dear Mr. Otis and Mr. Bocklund,

Is metastability in anyway integrated in this module? I mean: is it possible to plot phase diagrams with metastable phases and to study thermodynamic properties of metastable phases?

Best regards,
António Rocha

**Comment by richardotis** [comment]
Hi António, thank you for your message. It is possible to study metastability; in fact, this is the essence of the CALPHAD method. In a CALPHAD model the Gibbs energy is defined for all phases in the system. As long as the particular phase of interest is included in the model, it is possible to plot the phase diagram and compute thermodynamic properties. Individual phases can be included or excluded on the phase diagram or in the property calculation as well.

**Comment by richardotis** [comment]
If you can explain a bit more about what you're interested in studying, I can help you figure out how to do it using pycalphad.

**Comment by tjrocha7** [comment]
I just wanted to know if it was possible. My question arose because I thought phases were only listed on databases if they were stable and metastable phases weren't always included. I just want to plot metastable states along with stable in Fe-Ni systems and relate phase transitions in the phase diagrams with the graphs of thermodynamic properties.

**Comment by tjrocha7** [comment]
By the way, I'm having trouble in finding .tdb databases for Fe-Ni systems. Do you know where I could find it?

**Comment by richardotis** [comment]
The decision to include particular phases is up to the modeler who creates the database. For example, cementite is customarily included in the Fe-C system even though it's technically metastable. It usually depends on how well-studied a particular phase and how easy it is for the modeler to get data for it.

The `points`  keyword argument in `calculate()` is useful for fixing the sublattice site fractions and plotting properties. You could use this to fix a particular metastable configuration and then plot the heat capacity as a function of temperature, for example.

@bocklund can probably help you find some Fe-Ni databases.

**Comment by bocklund** [comment]
It looks like you can get the databases from the corresponding author of this paper [http://dx.doi.org/10.1016/j.intermet.2010.02.026](http://dx.doi.org/10.1016/j.intermet.2010.02.026)

**Comment by bocklund** [comment]
This page also has one you can download for free, once you sign up [http://cpddb.nims.go.jp/cpddb/fe-elem/feni/feni.htm](http://cpddb.nims.go.jp/cpddb/fe-elem/feni/feni.htm)

**Comment by tjrocha7** [comment]
@richardotis Thank you for your suggestions. I'm new to the Calphad method and my Materials Science knowledge is more about characterization then theoretical, therefore these questions.

@bocklund Already done it. Thank you as well!

**Comment by bocklund** [comment]
@tjrocha7 I am closing this now. If you have more questions about using pycalphad or anything that is not related to a technical bug in pycalphad, I encourage you use the [pycalphad Google group](https://groups.google.com/d/forum/pycalphad).
