### ISSUE TITLE
autowrap fails to import compiled files on macOS

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#65]
Using `GNU Fortran (Homebrew GCC 6.3.0_1) 6.3.0` compiler on macOS 10.12.2  results in failures to import compiled Fortran files in autowrap. The problem seems to be that the compiler flags passed with the `f2py`backend in custom_autowrap.autowrap generate debug symbol files (`.dSYM`) files alongside the compiled files. 

The quick fix is to just filter out those files, e.g. with a blacklist by appending 
```
    blacklist = ['dSYM']
    npath = [x for x in npath if x.split('.')[-1] not in blacklist]
```
after line 101. 

A more permanent solution would be to explicitly turn off such compiler flags and write a test to confirm. Currently, the tests fail on the above machine because of this bug, but this does not appear to be getting caught by CI.

**Comment by richardotis** [comment]
I'm fine with either approach for patching. We really need to get the CI issues worked out so that there are reliable tests again.

**Comment by bocklund** [comment]
I do want to mention here (so we can reference this) that a viable alternative to a blacklist would be a whitelist with valid file extensions. In principle, whichever list is smaller should be easier to maintain. Here I think excluding special cases is better than including normal cases. Not filtering out files correctly (`len(path)>1`) will raise an error on import, so either approach is technically fine.
