### ISSUE TITLE
errors in line calculation

### ISSUE THREAD

**Issue by broshe** [pycalphad/pycalphad#76]
Hello, I am trying to do a line caluclation with pycalphad.
Al-Fe chosen as model system.
I am using the latest pycalphad and anaconda python on linux.
The attached script caused warning and error messages and did not run correctly.
The error message is attached below.
Also, I attached the two log files mentioned in the error message.
What's wrong?

[ebrosh@ebrosh-laptop Al-Fe-solidification]$ python try_pycalphad_linemap.py
Initialize (1/3): 100%|████████████████████████| 2/2 [00:00<00:00,  2.61phase/s]
/home/ebrosh/anaconda3/lib/python3.5/site-packages/pycalphad/core/equilibrium.py:109: RuntimeWarning: invalid value encountered in less_equal
  unstable_phases = np.nonzero(properties['NP'].values[multi_index] <= MIN_SITE_FRACTION)
Preserved Files:  []
Preserved Files:  ['/tmp/ufuncify_btb9xrf9.log', '/tmp/ufuncify_efrlo334.log']
Traceback (most recent call last):
  File "try_pycalphad_linemap.py", line 26, in <module>
    eq = equilibrium(db, ['AL', 'FE', 'VA'], my_phases, {v.X('FE'): 1.5e-3, v.T: Tvector, v.P: 101325})
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/pycalphad/core/tempfilemanager.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/pycalphad/core/equilibrium.py", line 886, in equilibrium
    results = dask.compute(*res, get=dask.multiprocessing.get)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/dask/multiprocessing.py", line 86, in get
    dumps=dumps, loads=loads, **kwargs)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/dask/async.py", line 493, in get_async
    raise(remote_exception(res, tb))
dask.async.IndexError: index 1 is out of bounds for axis 0 with size 1

Traceback
---------
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/dask/async.py", line 268, in execute_task
    result = _execute_task(task, data)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/pycalphad/core/tempfilemanager.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/pycalphad/core/equilibrium.py", line 366, in _solve_eq_at_conditions
    [b[a] for a, b in zip(it.multi_index, properties['GM'].coords.values())]))
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/pycalphad/core/equilibrium.py", line 366, in <listcomp>
    [b[a] for a, b in zip(it.multi_index, properties['GM'].coords.values())]))
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/xarray/core/dataarray.py", line 469, in __getitem__
    return self.isel(**self._item_key_to_dict(key))
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/xarray/core/dataarray.py", line 657, in isel
    ds = self._to_temp_dataset().isel(drop=drop, **indexers)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/xarray/core/dataset.py", line 1119, in isel
    new_var = var.isel(**var_indexers)
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/xarray/core/variable.py", line 548, in isel
    return self[tuple(key)]
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/xarray/core/variable.py", line 1192, in __getitem__
    values = self._indexable_data[key]
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/xarray/core/indexing.py", line 537, in __getitem__
    result = self.array[key]
  File "/home/ebrosh/anaconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 1423, in __getitem__
    return getitem(key)

[script_causes_errors.zip](https://github.com/pycalphad/pycalphad/files/926109/script_causes_errors.zip)

**Comment by bocklund** [comment]
Can you please upload an unzipped file or paste your script here?

**Comment by broshe** [comment]
Here is the script
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 17 18:09:26 2017

@author: ebrosh
"""

import matplotlib.pyplot as plt
from pycalphad import equilibrium
from pycalphad import Database, Model
import pycalphad.variables as v
import numpy as np
from pycalphad.plot.utils import phase_legend



db = Database('/home/ebrosh/Documents/ebroshWorks/tcworks/Al-Fe-solidification/alfe_sei.TDB')
phase_names=sorted(list(db.phases.keys()))

my_phases = ['LIQUID', 'FCC_A1']
phase_handles, phasemap = phase_legend(my_phases)

Tvector=np.arange(900.0,950.0,1.0)

eq = equilibrium(db, ['AL', 'FE', 'VA'], my_phases, {v.X('FE'): 1.5e-3, v.T: Tvector, v.P: 101325})

print(eq)

plt.figure()

for name in my_phases:
    phase_indices = np.nonzero(eq.Phase.values == name)
    plt.scatter(np.take(eq['T'].values, phase_indices[1]), eq.NP.values[phase_indices], color=phasemap[name])
plt.gca().legend(phase_handles, my_phases, loc='lower right')

plt.show(block=False)

**Comment by richardotis** [comment]
I think this problem is fixed in the development version of pycalphad. It's been a while since our last public release, so I think we should try to get a new release out soon. Let me chat with @bocklund about what our remaining issues are with getting pycalphad 0.5 released so you can go about your work.

**Comment by richardotis** [comment]
For what it's worth, this is the result I get for your calculation. Some of the temperatures did not converge all the way. I'm still working on improving the solver.

![image](https://cloud.githubusercontent.com/assets/6405510/25098708/728ed686-235e-11e7-8252-abb6bb6cb795.png)

**Comment by richardotis** [comment]
The energy surface here is somewhat tricky:
```python
import numpy as np
from pycalphad.plot.utils import phase_legend
fig = plt.figure()
phase_handles, phasemap = phase_legend(['LIQUID', 'FCC_A1'])
for phase, color in phasemap.items():
    res = calculate(db, ['AL', 'FE', 'VA'], phase, T=922, P=101325)
    order = np.argsort(res.X[0,0].sel(component='FE'))
    x = res.X[0,0].sel(component='FE').values[order]
    y = res.GM[0,0].values[order]
    fig.gca().plot(x, y, c=color)
#fig.gca().set_xlim((0, 1e-2))
#fig.gca().set_ylim((-38000, -36000))
fig.gca().set_xlabel('X(FE)')
fig.gca().set_ylabel('Molar Gibbs Energy (J/mol-atom)')
fig.gca().set_title('T = 922 K')
fig.gca().legend(phase_handles, ['LIQUID', 'FCC_A1'], loc='lower right')
```
![image](https://cloud.githubusercontent.com/assets/6405510/25108447/a88369f6-238a-11e7-9b0b-3b80abf9bbe6.png)

Zoomed into the area of interest:
![image](https://cloud.githubusercontent.com/assets/6405510/25108570/8fdddaac-238b-11e7-8b7d-12ed3f57c5a5.png)

**Comment by broshe** [comment]
Is it possible to pass some arguments to the calculation engine that will ensure convergence?
I tried to enlarge pdens=1e6 but this did not help.
Eli

**Comment by richardotis** [comment]
@broshe Hi Eli, Brandon and I are working hard to release a new version of pycalphad which will solve your problem. We expect to have the new release ready in 7-10 days.

**Comment by richardotis** [comment]
Progress. I just need to clean up the last few changes on my local branch and start addressing the comments from code review
![image](https://cloud.githubusercontent.com/assets/6405510/25446103/4c020340-2a65-11e7-88af-941e08d5e07a.png)
![image](https://cloud.githubusercontent.com/assets/6405510/25446107/505ba7fc-2a65-11e7-89e3-b0c5f1b14404.png)

**Comment by broshe** [comment]
Can I test it before the release?
Eli

**Comment by richardotis** [comment]
@broshe Dear Eli, you can test the new version using our interactive online Jupyter Notebook demo (may take a minute or two to load): http://mybinder.org/repo/pycalphad/binder
Note that nothing will be saved after you close the browser window, so you should download your result if you want to keep it. The interactive demo is an experiment for us, so please let us know if you have questions or comments.

**Comment by richardotis** [comment]
@broshe Dear Eli, the new version of pycalphad is released. Please update and let us know if your issue is solved.

**Comment by broshe** [comment]
I checked with the new version and the calculation works now.
The issue can be closed.
Thanks,
Eli
