### ISSUE TITLE
Support X_FE style notation in pycalphad.core.utils.unpack_conditions()

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#87]

**Comment by richardotis** [comment]
Is this a blocker for 0.5?

**Comment by bocklund** [comment]
No. This is pretty easy to implement IMO and v.X notation is only 5 more characters. It would make a good first PR

**Comment by bocklund** [comment]
I'm going to close this issue because using pycalphad variables should be preferred as we introduce more flexibility in conditions via pycalphad 0.8.

cc @hui1sun
