### ISSUE TITLE
`calculate` does not use the FallbackModel mechanics.

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#89]
If we are exposing `calculate` as public API, should we use the same FallbackModel inside so users don't get NotImplementedErrors with the CompiledModel?

**Comment by richardotis** [comment]
Yes, you can fix this.

On May 4, 2017 12:15 PM, Brandon Bocklund <notifications@github.com> wrote:

If we are exposing calculate as public API, should we use the same FallbackModel inside so users don't get NotImplementedErrors with the CompiledModel?
